# Generated by Django 5.1.6 on 2026-03-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_userprofile_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="is_email_verified",
            new_name="email_verified_yn",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="is_paid",
            new_name="paid_yn",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="회사명"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="영업허가번호 또는 품목제조보고번호",
                max_length=100,
                verbose_name="인허가번호",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="manufacturer_address",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="제조원 소재지"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="manufacturer_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="제조원"),
        ),
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business_report", "영업신고증"),
                            ("haccp", "HACCP 인증서"),
                            ("manufacture_license", "제조업 영업등록증"),
                            ("iso", "ISO 인증서"),
                            ("organic", "유기농인증서"),
                            ("etc", "기타"),
                        ],
                        default="etc",
                        max_length=30,
                        verbose_name="서류 종류",
                    ),
                ),
                (
                    "doc_name",
                    models.CharField(
                        blank=True,
                        help_text="비워두면 서류 종류 이름으로 자동 저장됩니다",
                        max_length=200,
                        verbose_name="서류명",
                    ),
                ),
                (
                    "doc_file",
                    models.FileField(
                        upload_to="company_documents/%Y/", verbose_name="파일"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="메모"),
                ),
                (
                    "linked_document_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="불러오기 시 자동 적용될 제품 문서 구분",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_documents",
                        to="products.documenttype",
                        verbose_name="제품 문서 구분",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "회사 고정 서류",
                "verbose_name_plural": "회사 고정 서류",
                "ordering": ["doc_type", "-uploaded_at"],
            },
        ),
    ]
