# Generated by Django 5.2.17 on 2026-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_rename_is_email_verified_userprofile_email_verified_yn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='list_prefs',
            field=models.JSONField(blank=True, default=dict, verbose_name='목록 화면 설정'),
        ),
    ]
