# Generated by Django 5.1.15 on 2026-08-15 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("label", "0019_mylabel_basic_display_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="label_editor/%Y/%m/%d/", verbose_name="이미지"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="원본 파일명"),
                ),
                ("uploaded_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_images",
                        to="label.mylabel",
                        verbose_name="표시사항",
                    ),
                ),
            ],
            options={
                "verbose_name": "에디터 이미지",
                "verbose_name_plural": "에디터 이미지 목록",
                "db_table": "label_editor_image",
            },
        ),
        migrations.CreateModel(
            name="LabelLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canvas_width",
                    models.PositiveIntegerField(
                        default=800, verbose_name="캔버스 너비(px)"
                    ),
                ),
                (
                    "canvas_height",
                    models.PositiveIntegerField(
                        default=600, verbose_name="캔버스 높이(px)"
                    ),
                ),
                (
                    "grid_size",
                    models.PositiveIntegerField(
                        default=10, verbose_name="그리드 크기(px)"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff", max_length=20, verbose_name="배경색"
                    ),
                ),
                ("elements", models.JSONField(default=list, verbose_name="개체 목록")),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout",
                        to="label.mylabel",
                        verbose_name="표시사항",
                    ),
                ),
            ],
            options={
                "verbose_name": "라벨 레이아웃",
                "verbose_name_plural": "라벨 레이아웃 목록",
                "db_table": "label_editor_layout",
            },
        ),
    ]
