# Generated by Django 5.1.4 on 2025-01-12 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='사용자 전화번호', max_length=15)),
                ('address', models.TextField(blank=True, help_text='사용자 주소')),
                ('birth_date', models.DateField(blank=True, help_text='사용자 생년월일', null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='사용자 프로필 이미지', null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
