let counter = 0;

export const generateId = () => `el_${Date.now()}_${counter++}`;

export const createTextBox = (x = 100, y = 100) => ({
  id: generateId(),
  type: 'text_box',
  x, y,
  width: 200,
  height: 60,
  rotation: 0,
  opacity: 1,
  zIndex: 0,
  locked: false,
  visible: true,
  name: '텍스트',
  text: '텍스트를 입력하세요',
  fontSize: 14,
  fontFamily: 'Noto Sans KR',
  fontStyle: 'normal',
  textColor: '#000000',
  textAlign: 'left',
  lineHeight: 1.2,
  letterSpacing: 0,
  padding: 6,
  backgroundColor: '#ffffff',
  borderColor: '#000000',
  borderWidth: 1,
  borderStyle: 'solid',
  cornerRadius: 0,
});

export const createTextPair = (x = 100, y = 100) => ({
  id: generateId(),
  type: 'text_pair',
  x, y,
  width: 300,
  height: 36,
  rotation: 0,
  opacity: 1,
  zIndex: 0,
  locked: false,
  visible: true,
  name: '라벨 쌍',
  labelText: '식품유형',
  valueText: '값을 입력하세요',
  labelRatio: 0.35,
  fontSize: 13,
  fontFamily: 'Noto Sans KR',
  fontStyle: 'normal',
  textColor: '#000000',
  lineHeight: 1.2,
  padding: 5,
  backgroundColor: '#ffffff',
  labelBackgroundColor: '#f5f5f5',
  borderColor: '#000000',
  borderWidth: 1,
  dividerColor: '#000000',
  dividerWidth: 1,
  cornerRadius: 0,
});

export const createImageBox = (x = 100, y = 100, imageUrl = '', filename = '') => ({
  id: generateId(),
  type: 'image',
  x, y,
  width: 150,
  height: 150,
  rotation: 0,
  opacity: 1,
  zIndex: 0,
  locked: false,
  visible: true,
  name: filename || '이미지',
  imageUrl,
  borderColor: '#cccccc',
  borderWidth: 0,
  cornerRadius: 0,
});
