-- ExpiryRecommendation 테이블 데이터 삽입 쿼리
-- MySQL Workbench에서 실행 가능

-- 기존 데이터 삭제 (선택사항)
-- DELETE FROM expiry_recommendation;

-- 소비기한 권장 데이터 삽입
INSERT INTO expiry_recommendation (food_type, shelf_life, unit, created_at, updated_at) VALUES
('과자', '12', 'months', NOW(), NOW()),
('빵류', '14', 'days', NOW(), NOW()),
('떡류', '10', 'days', NOW(), NOW()),
('추잉껌', '24', 'months', NOW(), NOW()),
('캔디류', '24', 'months', NOW(), NOW()),
('기타가공품', '제품별', NULL, NOW(), NOW()),
('효모식품', '24', 'months', NOW(), NOW()),
('시리얼류', '18', 'months', NOW(), NOW()),
('찐쌀', '12', 'months', NOW(), NOW()),
('효소식품', '24', 'months', NOW(), NOW()),
('곡류가공품', '24', 'months', NOW(), NOW()),
('과·채가공품', '12', 'months', NOW(), NOW()),
('기타농산가공품', '제품별', NULL, NOW(), NOW()),
('두류가공품', '24', 'months', NOW(), NOW()),
('서류가공품', '24', 'months', NOW(), NOW()),
('땅콩 또는 견과류가공품', '12', 'months', NOW(), NOW()),
('땅콩버터', '12', 'months', NOW(), NOW()),
('밀가루', '12', 'months', NOW(), NOW()),
('영영강화 밀가루', '12', 'months', NOW(), NOW()),
('전분', '24', 'months', NOW(), NOW()),
('전분가공품', '24', 'months', NOW(), NOW()),
('당류가공품', '36', 'months', NOW(), NOW()),
('당시럽류', '36', 'months', NOW(), NOW()),
('포도당', '36', 'months', NOW(), NOW()),
('과당', '36', 'months', NOW(), NOW()),
('기타과당', '36', 'months', NOW(), NOW()),
('기타설탕', '36', 'months', NOW(), NOW()),
('설탕', '36', 'months', NOW(), NOW()),
('기타 엿', '36', 'months', NOW(), NOW()),
('덱스트린', '36', 'months', NOW(), NOW()),
('물엿', '36', 'months', NOW(), NOW()),
('올리고당', '36', 'months', NOW(), NOW()),
('올리고당가공품', '36', 'months', NOW(), NOW()),
('곤충가공식품', '24', 'months', NOW(), NOW()),
('추출가공식품', '제품별', NULL, NOW(), NOW()),
('기타 동물성가공식품', '제품별', NULL, NOW(), NOW()),
('기타식육 또는 기타알', '제품별', NULL, NOW(), NOW()),
('자라분말', '제품별', NULL, NOW(), NOW()),
('자라분말제품', '제품별', NULL, NOW(), NOW()),
('자라유제품', '제품별', NULL, NOW(), NOW()),
('가공두부', '27', 'days', NOW(), NOW()),
('두부', '27', 'days', NOW(), NOW()),
('묵류', '27', 'days', NOW(), NOW()),
('유바', '27', 'days', NOW(), NOW()),
('건면', '12', 'months', NOW(), NOW()),
('생면', '60', 'days', NOW(), NOW()),
('숙면', '60', 'days', NOW(), NOW()),
('유탕면', '12', 'months', NOW(), NOW()),
('로열제리', '36', 'months', NOW(), NOW()),
('로열젤리제품', '36', 'months', NOW(), NOW()),
('벌꿀', '36', 'months', NOW(), NOW()),
('벌집꿀', '36', 'months', NOW(), NOW()),
('사양벌꿀', '36', 'months', NOW(), NOW()),
('사양벌집꿀', '36', 'months', NOW(), NOW()),
('가공화분', '24', 'months', NOW(), NOW()),
('화분함유제품', '24', 'months', NOW(), NOW()),
('빙과', '24', 'months', NOW(), NOW()),
('비유지방아이스크림', '24', 'months', NOW(), NOW()),
('샤베트', '24', 'months', NOW(), NOW()),
('아이스밀크', '24', 'months', NOW(), NOW()),
('아이스크림', '24', 'months', NOW(), NOW()),
('저지방아이스크림', '24', 'months', NOW(), NOW()),
('비유지방아이스크림믹스', '24', 'months', NOW(), NOW()),
('샤베트믹스', '24', 'months', NOW(), NOW()),
('아이스밀크믹스', '24', 'months', NOW(), NOW()),
('아이스크림믹스', '24', 'months', NOW(), NOW()),
('저지방아이스크림믹스', '24', 'months', NOW(), NOW()),
('식용얼음', '1', 'months', NOW(), NOW()),
('어업용얼음', '1', 'months', NOW(), NOW()),
('기타 수산물가공품', '제품별', NULL, NOW(), NOW()),
('조미김', '8', 'months', NOW(), NOW()),
('한천', '24', 'months', NOW(), NOW()),
('건어포', '24', 'months', NOW(), NOW()),
('기타 건포류', '24', 'months', NOW(), NOW()),
('조미건어포', '12', 'months', NOW(), NOW()),
('기타 어육가공품', '제품별', NULL, NOW(), NOW()),
('어묵', '42', 'days', NOW(), NOW()),
('어육반제품', '제품별', NULL, NOW(), NOW()),
('어육살', '제품별', NULL, NOW(), NOW()),
('어육소시지', '제품별', NULL, NOW(), NOW()),
('연육', '제품별', NULL, NOW(), NOW()),
('액젓', '36', 'months', NOW(), NOW()),
('양념젓갈', '36', 'months', NOW(), NOW()),
('젓갈', '36', 'months', NOW(), NOW()),
('조미액젓', '36', 'months', NOW(), NOW()),
('기타동물성유지', '24', 'months', NOW(), NOW()),
('식용돈지', '24', 'months', NOW(), NOW()),
('식용우지', '24', 'months', NOW(), NOW()),
('어유', '24', 'months', NOW(), NOW()),
('고추씨기름', '24', 'months', NOW(), NOW()),
('기타식물성유지', '24', 'months', NOW(), NOW()),
('들기름', '18', 'months', NOW(), NOW()),
('땅콩기름(낙화생유)', '18', 'months', NOW(), NOW()),
('목화씨기름(면실유)', '18', 'months', NOW(), NOW()),
('미강유(현미유)', '18', 'months', NOW(), NOW()),
('야자유', '18', 'months', NOW(), NOW()),
('옥수수기름(옥배유)', '18', 'months', NOW(), NOW()),
('올리브유', '18', 'months', NOW(), NOW()),
('참기름', '18', 'months', NOW(), NOW()),
('채종유(유채유 또는 카놀라유)', '18', 'months', NOW(), NOW()),
('추출들깨유', '18', 'months', NOW(), NOW()),
('추출참깨유', '18', 'months', NOW(), NOW()),
('콩기름(대두유)', '18', 'months', NOW(), NOW()),
('팜스테아린유', '18', 'months', NOW(), NOW()),
('팜올레인유', '18', 'months', NOW(), NOW()),
('팜유', '18', 'months', NOW(), NOW()),
('팜핵유', '18', 'months', NOW(), NOW()),
('해바라기유', '18', 'months', NOW(), NOW()),
('홍화유(사플라워유 또는 잇꽃유)', '18', 'months', NOW(), NOW()),
('가공유지', '18', 'months', NOW(), NOW()),
('마가린', '18', 'months', NOW(), NOW()),
('모조치즈', '18', 'months', NOW(), NOW()),
('쇼트닝', '18', 'months', NOW(), NOW()),
('식물성크림', '12', 'months', NOW(), NOW()),
('향미유', '18', 'months', NOW(), NOW()),
('혼합식용유', '18', 'months', NOW(), NOW()),
('건조저장육류', '6', 'months', NOW(), NOW()),
('베이컨류', '66', 'days', NOW(), NOW()),
('식육간편조리세트', '제품별', NULL, NOW(), NOW()),
('식육추출가공품', '제품별', NULL, NOW(), NOW()),
('식육함유가공품', '제품별', NULL, NOW(), NOW()),
('포장육', '제품별', NULL, NOW(), NOW()),
('발효소시지', '90', 'days', NOW(), NOW()),
('소시지', '56', 'days', NOW(), NOW()),
('혼합소시지', '66', 'days', NOW(), NOW()),
('갈비가공품', '제품별', NULL, NOW(), NOW()),
('분쇄가공육제품', '30', 'days', NOW(), NOW()),
('식육케이싱', '제품별', NULL, NOW(), NOW()),
('양념육', '30', 'days', NOW(), NOW()),
('천연케이싱', '제품별', NULL, NOW(), NOW()),
('생햄', '90', 'days', NOW(), NOW()),
('프레스햄', '66', 'days', NOW(), NOW()),
('햄', '57', 'days', NOW(), NOW()),
('알함유가공품', '제품별', NULL, NOW(), NOW()),
('난백분', '24', 'months', NOW(), NOW()),
('난백액', '10', 'days', NOW(), NOW()),
('난황분', '24', 'months', NOW(), NOW()),
('난황액', '10', 'days', NOW(), NOW()),
('알가열제품', '제품별', NULL, NOW(), NOW()),
('전란분', '24', 'months', NOW(), NOW()),
('전란액', '10', 'days', NOW(), NOW()),
('피단', '제품별', NULL, NOW(), NOW()),
('버터유', '12', 'months', NOW(), NOW()),
('산양유', '제품별', NULL, NOW(), NOW()),
('유단백가수분해식품', '제품별', NULL, NOW(), NOW()),
('유당', '12', 'months', NOW(), NOW()),
('유함유가공품', '제품별', NULL, NOW(), NOW()),
('가공유', '24', 'days', NOW(), NOW()),
('강화우유', '15', 'days', NOW(), NOW()),
('유당분해우유', '15', 'days', NOW(), NOW()),
('유산균첨가우유', '15', 'days', NOW(), NOW()),
('가공연유', '12', 'months', NOW(), NOW()),
('가당연유', '12', 'months', NOW(), NOW()),
('가당탈지연유', '12', 'months', NOW(), NOW()),
('농축우유', '12', 'months', NOW(), NOW()),
('탈지농축우유', '12', 'months', NOW(), NOW()),
('농후발효유', '32', 'days', NOW(), NOW()),
('농후크림발효유', '32', 'days', NOW(), NOW()),
('발효버터유', '12', 'months', NOW(), NOW()),
('발효유', '32', 'days', NOW(), NOW()),
('발효유분말', '12', 'months', NOW(), NOW()),
('크림발효유', '32', 'days', NOW(), NOW()),
('가공버터', '12', 'months', NOW(), NOW()),
('버터', '12', 'months', NOW(), NOW()),
('버터오일', '12', 'months', NOW(), NOW()),
('가당분유', '18', 'months', NOW(), NOW()),
('전지분유', '18', 'months', NOW(), NOW()),
('탈지분유', '18', 'months', NOW(), NOW()),
('혼합분유', '18', 'months', NOW(), NOW()),
('우유', '15', 'days', NOW(), NOW()),
('환원유', '15', 'days', NOW(), NOW()),
('농축유청', '12', 'months', NOW(), NOW()),
('유청', '12', 'months', NOW(), NOW()),
('유청단백분말', '12', 'months', NOW(), NOW()),
('가공유크림', '12', 'months', NOW(), NOW()),
('유크림', '12', 'months', NOW(), NOW()),
('가공치즈', '12', 'months', NOW(), NOW()),
('치즈', '18', 'months', NOW(), NOW()),
('인삼·홍삼음료', '12', 'months', NOW(), NOW()),
('커피', '12', 'months', NOW(), NOW()),
('과·채음료', '12', 'months', NOW(), NOW()),
('과·채주스', '12', 'months', NOW(), NOW()),
('농축과·채즙', '12', 'months', NOW(), NOW()),
('음료베이스', '12', 'months', NOW(), NOW()),
('혼합음료', '12', 'months', NOW(), NOW()),
('고형차', '24', 'months', NOW(), NOW()),
('액상차', '12', 'months', NOW(), NOW()),
('침출차', '24', 'months', NOW(), NOW()),
('가공두유', '12', 'months', NOW(), NOW()),
('원액두유', '12', 'months', NOW(), NOW()),
('기타발효음료', '제품별', NULL, NOW(), NOW()),
('유산균음료', '26', 'days', NOW(), NOW()),
('효모음료', '제품별', NULL, NOW(), NOW()),
('탄산수', '12', 'months', NOW(), NOW()),
('탄산음료', '12', 'months', NOW(), NOW()),
('개량메주', '12', 'months', NOW(), NOW()),
('고추장', '24', 'months', NOW(), NOW()),
('기타장류', '24', 'months', NOW(), NOW()),
('된장', '24', 'months', NOW(), NOW()),
('산분해간장', '24', 'months', NOW(), NOW()),
('양조간장', '24', 'months', NOW(), NOW()),
('청국장', '24', 'months', NOW(), NOW()),
('춘장', '24', 'months', NOW(), NOW()),
('한식간장', '24', 'months', NOW(), NOW()),
('한식된장', '24', 'months', NOW(), NOW()),
('한식메주', '24', 'months', NOW(), NOW()),
('혼합간장', '24', 'months', NOW(), NOW()),
('혼합장', '24', 'months', NOW(), NOW()),
('효소분해간장', '24', 'months', NOW(), NOW()),
('기타잼', '12', 'months', NOW(), NOW()),
('잼', '12', 'months', NOW(), NOW()),
('조림류', '12', 'months', NOW(), NOW()),
('김치', '6', 'months', NOW(), NOW()),
('김칫속', '6', 'months', NOW(), NOW()),
('당절임', '12', 'months', NOW(), NOW()),
('절임식품', '12', 'months', NOW(), NOW()),
('고춧가루', '12', 'months', NOW(), NOW()),
('실고추', '12', 'months', NOW(), NOW()),
('마요네즈', '12', 'months', NOW(), NOW()),
('복합조미식품', '12', 'months', NOW(), NOW()),
('소스', '12', 'months', NOW(), NOW()),
('토마토케첩', '12', 'months', NOW(), NOW()),
('가공소금', '60', 'months', NOW(), NOW()),
('기타소금', '60', 'months', NOW(), NOW()),
('재제소금', '60', 'months', NOW(), NOW()),
('정제소금', '60', 'months', NOW(), NOW()),
('천일염', '60', 'months', NOW(), NOW()),
('태움·용융소금', '60', 'months', NOW(), NOW()),
('발효식초', '24', 'months', NOW(), NOW()),
('희석초산', '24', 'months', NOW(), NOW()),
('카레(커리)', '24', 'months', NOW(), NOW()),
('카레(커리)분', '24', 'months', NOW(), NOW()),
('천연향신료', '24', 'months', NOW(), NOW()),
('향신료조제품', '24', 'months', NOW(), NOW()),
('주정', '36', 'months', NOW(), NOW()),
('기타 주류', '36', 'months', NOW(), NOW()),
('과실주', '36', 'months', NOW(), NOW()),
('맥주', '12', 'months', NOW(), NOW()),
('약주', '12', 'months', NOW(), NOW()),
('청주', '12', 'months', NOW(), NOW()),
('탁주', '12', 'months', NOW(), NOW()),
('리큐르', '36', 'months', NOW(), NOW()),
('브랜디', '36', 'months', NOW(), NOW()),
('소주', '36', 'months', NOW(), NOW()),
('위스키', '36', 'months', NOW(), NOW()),
('일반증류주', '36', 'months', NOW(), NOW()),
('만두', '12', 'months', NOW(), NOW()),
('만두피', '6', 'months', NOW(), NOW()),
('생식제품', '12', 'months', NOW(), NOW()),
('생식함유제품', '12', 'months', NOW(), NOW()),
('간편조리세트', '12', 'months', NOW(), NOW()),
('신선편의식품', '12', 'months', NOW(), NOW()),
('즉석섭취식품', '12', 'months', NOW(), NOW()),
('즉석조리식품', '12', 'months', NOW(), NOW()),
('밀크초콜릿', '24', 'months', NOW(), NOW()),
('준초콜릿', '24', 'months', NOW(), NOW()),
('초콜릿', '24', 'months', NOW(), NOW()),
('초콜릿가공품', '24', 'months', NOW(), NOW()),
('화이트초콜릿', '24', 'months', NOW(), NOW()),
('기타 코코아가공품', '24', 'months', NOW(), NOW()),
('코코아매스', '24', 'months', NOW(), NOW()),
('코코아버터', '24', 'months', NOW(), NOW()),
('코코아분말', '24', 'months', NOW(), NOW()),
('고령자용 영양조제식품', '18', 'months', NOW(), NOW()),
('기타영유아식', '18', 'months', NOW(), NOW()),
('성장기용조제식', '18', 'months', NOW(), NOW()),
('영·유아용 곡류조제식', '18', 'months', NOW(), NOW()),
('영·유아용 이유식', '12', 'months', NOW(), NOW()),
('영아용 조제식', '18', 'months', NOW(), NOW()),
('임산·수유부용 식품', '18', 'months', NOW(), NOW()),
('체중조절용 조제식품', '18', 'months', NOW(), NOW()),
('성장기용 조제유', '18', 'months', NOW(), NOW()),
('영아용 조제유', '18', 'months', NOW(), NOW()),
('기타환자용 영양조제식품', '12', 'months', NOW(), NOW()),
('선천성 대사질환자용 조제식품', '12', 'months', NOW(), NOW()),
('영.유아용 특수조제식품', '12', 'months', NOW(), NOW()),
('고혈압환자용 식단형 식품', '12', 'months', NOW(), NOW()),
('당뇨환자용 식단형 식품', '12', 'months', NOW(), NOW()),
('신장질환자용 식단형 식품', '12', 'months', NOW(), NOW()),
('암환자용 식단형 식품', '12', 'months', NOW(), NOW()),
('고혈압환자용 영양조제식품', '12', 'months', NOW(), NOW()),
('당뇨환자용 영양조제식품', '12', 'months', NOW(), NOW()),
('수분 및 전해질보충용 조제식품', '12', 'months', NOW(), NOW()),
('신장질환자용 영양조제식품', '12', 'months', NOW(), NOW()),
('암환자용 영양조제식품', '12', 'months', NOW(), NOW()),
('연하곤란자용 점도조절식품', '12', 'months', NOW(), NOW()),
('열량 및 영양공급용 식품', '12', 'months', NOW(), NOW()),
('일반 환자용 균형영양조제식품(균형영양조제식품)', '12', 'months', NOW(), NOW()),
('장질환자용 단백가수분해 영양조제식품', '12', 'months', NOW(), NOW()),
('폐질환자용 영양조제식품', '12', 'months', NOW(), NOW());

-- 데이터 확인 쿼리
SELECT COUNT(*) AS total_count FROM expiry_recommendation;
SELECT * FROM expiry_recommendation LIMIT 10;
