# Generated by Django 5.1.6 on 2025-05-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrativeAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Unknown Company", help_text="업체명", max_length=255
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(help_text="인허가번호", max_length=100),
                ),
                (
                    "action_name",
                    models.CharField(help_text="행정처분명", max_length=255),
                ),
                ("action_date", models.DateField(help_text="행정처분일")),
                ("details", models.TextField(blank=True, help_text="기타 세부 내용")),
            ],
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="API 키 생성 시간"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="API 키 갱신 시간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="API 이름", max_length=255)),
                ("url", models.URLField(help_text="API URL", max_length=500)),
                (
                    "start_date",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="시작일자(YYYYMMDD)",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "call_frequency_minutes",
                    models.IntegerField(default=1440, help_text="호출 주기 (분 단위)"),
                ),
                (
                    "last_called_at",
                    models.DateTimeField(
                        blank=True, help_text="마지막 호출 시간", null=True
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        choices=[("success", "성공"), ("failure", "실패")],
                        default="success",
                        help_text="마지막 호출 상태",
                        max_length=50,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        help_text="서비스 이름 (예: I1250)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_start_position",
                    models.IntegerField(
                        default=1,
                        help_text="마지막 요청 시작 위치 (중단 후 이어받기용)",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="API 키",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endpoints",
                        to="common.apikey",
                    ),
                ),
            ],
        ),
    ]
