# Generated by Django 5.1.6 on 2025-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiendpoint",
            name="use_reset_start_position",
            field=models.CharField(
                choices=[("Y", "초기화"), ("N", "유지")],
                default="Y",
                help_text="API 호출 시 last_start_position을 1로 초기화할지 여부 (Y: 초기화, N: 유지)",
                max_length=1,
            ),
        ),
    ]
