# Generated by Django 5.1.6 on 2026-03-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_useractivitylog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserActivityLog",
        ),
    ]
