# Generated by Django 5.1.6 on 2026-08-30 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_delete_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiValidationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField(help_text='서버 시간대 기준 날짜', verbose_name='사용일')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_validation_usage', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI검증 사용량',
                'verbose_name_plural': 'AI검증 사용량',
                'db_table': 'ai_validation_usage',
                'indexes': [models.Index(fields=['used_date'], name='idx_ai_usage_date')],
                'constraints': [models.UniqueConstraint(fields=('user', 'used_date'), name='uniq_ai_usage_user_date')],
            },
        ),
    ]
