# Generated by Django 5.1.6 on 2026-08-30 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_aivalidationusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrCorrection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=40, verbose_name='항목')),
                ('ocr_value', models.TextField(blank=True, default='', verbose_name='판독값')),
                ('final_value', models.TextField(blank=True, default='', verbose_name='사용자가 쓴 값')),
                ('corrected', models.BooleanField(default=False, verbose_name='고쳤는지')),
                ('confidence', models.CharField(blank=True, default='', max_length=10, verbose_name='판독 확신도')),
                ('model', models.CharField(blank=True, default='', max_length=40, verbose_name='판독 모델')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_corrections', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '판독 교정 이력',
                'verbose_name_plural': '판독 교정 이력',
                'db_table': 'ocr_correction',
                'indexes': [models.Index(fields=['field', 'corrected'], name='idx_ocr_corr_field'), models.Index(fields=['created_at'], name='idx_ocr_corr_date')],
            },
        ),
    ]
