# Generated by Django 5.1.6 on 2026-08-30 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_ocrcorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrcorrection',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='판독 방식'),
        ),
        migrations.AddIndex(
            model_name='ocrcorrection',
            index=models.Index(fields=['model', 'variant'], name='idx_ocr_corr_how'),
        ),
    ]
