# Generated by Django 5.1.6 on 2026-08-31 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_ocrcorrection_variant_ocrcorrection_idx_ocr_corr_how'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrcorrection',
            name='source',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='값의 출처'),
        ),
        migrations.CreateModel(
            name='OcrPromptVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='판 이름')),
                ('prompt', models.TextField(verbose_name='프롬프트 전문')),
                ('note', models.TextField(blank=True, default='', verbose_name='무엇을 바꿨는가')),
                ('active', models.BooleanField(default=False, verbose_name='사용 중')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='자동 초안')),
                ('last_score', models.FloatField(blank=True, null=True, verbose_name='최근 점수')),
                ('last_scored_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 측정 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='common.ocrpromptversion', verbose_name='바탕이 된 판')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_prompts', to=settings.AUTH_USER_MODEL, verbose_name='만든 사람')),
            ],
            options={
                'verbose_name': '판독 프롬프트 판',
                'verbose_name_plural': '판독 프롬프트 판',
                'db_table': 'ocr_prompt_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OcrBenchmarkRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=40, verbose_name='모델')),
                ('variant', models.CharField(default='whole', max_length=20, verbose_name='판독 방식')),
                ('use_api', models.BooleanField(default=False, verbose_name='등록 정보 대조')),
                ('case_count', models.IntegerField(default=0, verbose_name='정답지 수')),
                ('runs', models.IntegerField(default=1, verbose_name='회차')),
                ('mean_score', models.FloatField(default=0.0, verbose_name='평균 점수')),
                ('detail', models.JSONField(default=dict, verbose_name='상세')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_benchmark_runs', to=settings.AUTH_USER_MODEL, verbose_name='실행한 사람')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_runs', to='common.ocrpromptversion', verbose_name='프롬프트 판')),
            ],
            options={
                'verbose_name': '판독 정확도 측정',
                'verbose_name_plural': '판독 정확도 측정',
                'db_table': 'ocr_benchmark_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OcrTruthCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='이름')),
                ('image', models.ImageField(upload_to='ocr_truth/%Y/%m/', verbose_name='표시사항 사진')),
                ('crop_box', models.JSONField(blank=True, null=True, verbose_name='읽을 영역')),
                ('report_no', models.CharField(blank=True, default='', max_length=32, verbose_name='품목보고번호')),
                ('expected', models.JSONField(default=dict, verbose_name='정답')),
                ('source', models.CharField(choices=[('manual', '직접 입력'), ('draft', '판독 초안을 수정'), ('label', '검증된 표시사항에서')], default='manual', max_length=10, verbose_name='정답의 출처')),
                ('verified', models.BooleanField(default=False, verbose_name='정답 확인됨')),
                ('note', models.TextField(blank=True, default='', verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_truth_cases', to=settings.AUTH_USER_MODEL, verbose_name='등록한 사람')),
            ],
            options={
                'verbose_name': '판독 정답지',
                'verbose_name_plural': '판독 정답지',
                'db_table': 'ocr_truth_case',
                'ordering': ['-created_at'],
            },
        ),
    ]
