# Generated by Django 5.2.17 on 2026-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_ocrcorrection_source_ocrpromptversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtruthcase',
            name='expected_boxes',
            field=models.JSONField(blank=True, default=dict, verbose_name='정답 위치'),
        ),
    ]
