# Generated by Django 5.2.17 on 2026-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_ocrtruthcase_expected_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtruthcase',
            name='ocr_engine',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='OCR 엔진'),
        ),
        migrations.AddField(
            model_name='ocrtruthcase',
            name='ocr_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OCR 읽은 시각'),
        ),
        migrations.AddField(
            model_name='ocrtruthcase',
            name='ocr_text',
            field=models.TextField(blank=True, default='', verbose_name='OCR 원문'),
        ),
    ]
