# Generated by Django 5.2.17 on 2026-09-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_featureusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtruthcase',
            name='expected_diff',
            field=models.JSONField(blank=True, default=list, verbose_name='정말 다른 항목'),
        ),
        migrations.AddField(
            model_name='ocrtruthcase',
            name='label_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='내 표시사항'),
        ),
    ]
