# Generated by Django 5.2.17 on 2026-09-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_ocr_truth_design_compare'),
        ('label', '0032_nutrition_source_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtruthcase',
            name='source_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_truth_cases', to='label.mylabel', verbose_name='연결된 표시사항'),
        ),
    ]
