# Generated by Django 5.1.4 on 2025-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_date', models.CharField(max_length=10, verbose_name='처분 확정일자')),
                ('business_type', models.CharField(blank=True, max_length=60, null=True, verbose_name='업종명')),
                ('business_name', models.CharField(max_length=200, verbose_name='업소명')),
                ('road_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='도로명주소')),
                ('lotno_addr', models.CharField(blank=True, max_length=300, null=True, verbose_name='지번주소')),
                ('disposition_details', models.TextField(blank=True, max_length=100, null=True, verbose_name='처분사항')),
                ('administrative_id', models.TextField(max_length=20, verbose_name='행정처분번호')),
                ('licence_no', models.CharField(max_length=30, verbose_name='인허가번호')),
                ('representative_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='대표자명')),
                ('disposition_period', models.CharField(blank=True, max_length=30, null=True, verbose_name='처분기간')),
                ('notice_details', models.TextField(blank=True, max_length=100, null=True, verbose_name='안내사항')),
                ('violation_details', models.TextField(blank=True, max_length=3000, null=True, verbose_name='위반내용')),
                ('processing_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='처리부서')),
                ('manager_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자명')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='이메일')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
            ],
            options={
                'db_table': 'administrative_disposition',
            },
        ),
        migrations.CreateModel(
            name='CrawlingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True, verbose_name='지역')),
                ('target_url', models.URLField(verbose_name='크롤링 대상 URL')),
                ('crawling_period', models.IntegerField(default=1, verbose_name='크롤링 주기 (일 단위)')),
                ('description', models.TextField(blank=True, help_text='설명', null=True)),
            ],
            options={
                'db_table': 'crawling_setting',
            },
        ),
    ]
