# Generated by Django 5.1.6 on 2025-06-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="category",
        ),
        migrations.RemoveField(
            model_name="board",
            name="is_public",
        ),
        migrations.AddField(
            model_name="board",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="board_images/"),
        ),
        migrations.AddField(
            model_name="board",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="board",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="board_files/"),
        ),
    ]
