# Generated by Django 4.2.17 on 2025-01-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='API 이름', max_length=255)),
                ('url', models.URLField(help_text='API URL', max_length=500)),
                ('call_frequency_minutes', models.IntegerField(default=1440, help_text='호출 주기 (분 단위)')),
                ('last_called_at', models.DateTimeField(blank=True, help_text='마지막 호출 시간', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
