# Generated by Django 5.1.4 on 2025-01-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_apiendpoint_api_key_apikey_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Unknown Company', help_text='업체명', max_length=255)),
                ('registration_number', models.CharField(help_text='인허가번호', max_length=100)),
                ('action_name', models.CharField(help_text='행정처분명', max_length=255)),
                ('action_date', models.DateField(help_text='행정처분일')),
                ('details', models.TextField(blank=True, help_text='기타 세부 내용')),
            ],
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='last_status',
            field=models.CharField(choices=[('success', '성공'), ('failure', '실패')], default='success', help_text='마지막 호출 상태', max_length=50),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='API 키 생성 시간'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='API 키 갱신 시간'),
        ),
    ]
