# Generated by Django 5.1.4 on 2025-01-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_administrativeaction_apiendpoint_last_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='service_name',
            field=models.CharField(default='I1250', help_text='서비스 이름 (예: I1250)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiendpoint',
            name='api_key',
            field=models.ForeignKey(blank=True, help_text='API 키', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='common.apikey'),
        ),
    ]
