# Generated by Django 5.1.6 on 2025-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_apiendpoint_service_name_alter_apiendpoint_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='service_name',
            field=models.CharField(blank=True, help_text='서비스 이름 (예: I1250)', max_length=50, null=True),
        ),
    ]
