# Generated by Django 5.1.4 on 2026-03-08 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bom', '0002_rename_is_fields'),
        ('label', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIngredientMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_keyword', models.CharField(max_length=200, verbose_name='매칭 키워드')),
                ('match_score', models.FloatField(default=0.0, verbose_name='매칭 점수')),
                ('risk_level', models.CharField(choices=[('HIGH', '중요'), ('MED', '관심'), ('LOW', '일반')], default='LOW', max_length=4, verbose_name='등급')),
                ('risk_score', models.IntegerField(default=0, verbose_name='위해도 점수')),
                ('read_yn', models.BooleanField(db_index=True, default=False, verbose_name='확인 여부')),
                ('dismissed_yn', models.BooleanField(db_index=True, default=False, verbose_name='해당 없음')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_matches', to='label.myingredient', verbose_name='원료')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_news_matches', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '부적합-원료 연결',
                'verbose_name_plural': '부적합-원료 연결 목록',
                'db_table': 'regulatory_news_ingredient_match',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_keyword', models.CharField(max_length=200, verbose_name='매칭 키워드')),
                ('matched_ingredient', models.CharField(max_length=200, verbose_name='내 원료명')),
                ('match_score', models.FloatField(default=0.0, verbose_name='매칭 점수(0~100)')),
                ('risk_level', models.CharField(choices=[('HIGH', '중요 (원료+원산지+제조사 일치)'), ('MED', '관심 (원료+원산지 일치)'), ('LOW', '일반 (원료명만 일치)')], default='LOW', max_length=4, verbose_name='매칭 위해도')),
                ('risk_score', models.IntegerField(default=0, verbose_name='위해도 점수(0~100)')),
                ('risk_reasons', models.JSONField(blank=True, default=list, help_text='["원료명 일치(마늘종)", "원산지 일치(중국)"]', verbose_name='위해도 산정 근거')),
                ('read_yn', models.BooleanField(db_index=True, default=False, verbose_name='확인 여부')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 일시')),
                ('false_positive_yn', models.BooleanField(db_index=True, default=False, verbose_name='오탐지 신고')),
                ('false_positive_at', models.DateTimeField(blank=True, null=True, verbose_name='오탐지 신고 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('matched_bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_matches', to='bom.productbom', verbose_name='매칭된 BOM 항목')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_matches', to='label.mylabel', verbose_name='연관 제품')),
            ],
            options={
                'verbose_name': '부적합-제품 연결',
                'verbose_name_plural': '부적합-제품 연결 목록',
                'db_table': 'regulatory_news_product_match',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryMatchAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('dismissed', '해당 없음'), ('monitoring', '진행 중'), ('resolved', '조치 완료'), ('memo', '메모')], max_length=20, verbose_name='조치 유형')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('ingredient_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='regulatory.newsingredientmatch', verbose_name='원료 매칭')),
                ('product_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='regulatory.newsproductmatch', verbose_name='제품 매칭')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_actions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '매칭 조치 이력',
                'verbose_name_plural': '매칭 조치 이력 목록',
                'db_table': 'regulatory_match_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(blank=True, db_index=True, default='', help_text='수집 API 서비스 ID (I2620/I2640/I0490/I0470/I0480/import)', max_length=20, verbose_name='API 출처 코드')),
                ('source', models.CharField(choices=[('domestic', '국내식품 부적합'), ('import', '수입식품 부적합')], db_index=True, max_length=20, verbose_name='출처')),
                ('external_id', models.CharField(db_index=True, help_text='국내: cntntsSn, 수입: API 고유키', max_length=100, verbose_name='외부 고유번호')),
                ('product_name', models.CharField(db_index=True, max_length=300, verbose_name='부적합 제품명')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='업체명')),
                ('violation_reason', models.TextField(blank=True, verbose_name='부적합 사유')),
                ('raw_detail_text', models.TextField(blank=True, verbose_name='상세 원문')),
                ('ai_keywords', models.JSONField(default=list, help_text='원재료명 + 검출물질 배열 (매칭 및 UI 표시용)', verbose_name='AI 추출 키워드')),
                ('ai_issues', models.JSONField(blank=True, default=list, help_text='텍스트에 명시된 원재료 구조화 배열', verbose_name='AI 구조화 이슈')),
                ('ai_substances', models.JSONField(blank=True, default=list, help_text='텍스트에 명시된 검출 물질명 배열', verbose_name='검출 물질')),
                ('violation_type', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='위반유형 코드')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI 요약')),
                ('ai_parsed', models.BooleanField(db_index=True, default=False, verbose_name='AI 분석 완료')),
                ('risk_level', models.CharField(choices=[('HIGH', '중요'), ('MED', '관심'), ('LOW', '일반')], default='MED', max_length=4, verbose_name='위험도')),
                ('event_date', models.DateField(blank=True, db_index=True, help_text='imp_insp=수입검사부적합일, 국내=처분·회수일', null=True, verbose_name='발생/처분일')),
                ('collected_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='수집일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '부적합 정보',
                'verbose_name_plural': '부적합 정보 목록',
                'db_table': 'regulatory_news',
                'ordering': [models.OrderBy(models.F('event_date'), descending=True, nulls_last=True), '-collected_date', '-created_at'],
                'indexes': [models.Index(fields=['source', 'collected_date'], name='regulatory__source_034e72_idx'), models.Index(fields=['ai_parsed'], name='regulatory__ai_pars_696a54_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.AddField(
            model_name='newsproductmatch',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='regulatory.regulatorynews', verbose_name='부적합 정보'),
        ),
        migrations.AddField(
            model_name='newsingredientmatch',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_matches', to='regulatory.regulatorynews', verbose_name='부적합 정보'),
        ),
        migrations.AddIndex(
            model_name='newsproductmatch',
            index=models.Index(fields=['product', 'read_yn'], name='regulatory__product_9b16bc_idx'),
        ),
        migrations.AddIndex(
            model_name='newsproductmatch',
            index=models.Index(fields=['false_positive_yn'], name='regulatory__false_p_b61969_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsproductmatch',
            unique_together={('news', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='newsingredientmatch',
            unique_together={('news', 'user', 'ingredient')},
        ),
    ]
