# Generated by Django 5.1.4
# 이름을 서버에 이미 적용 기록된 마이그레이션명('0003_inspectionmatch_fcm_sent_at')과
# 일치시켰습니다. 로컬에만 있던 0003_fix_inspection_last_updt_dtm_length,
# 0004_collected_date_from_api, 0005_inspectionmatch_fcm_sent_at 3개는 한 번도
# git으로 관리되지 않았고, 서버에는 이 3개 변경사항이 이미 하나로 합쳐진 채
# 적용되어 있었습니다. 그 상태와 동일하게 스쿼시했습니다.

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0002_inspection_result_and_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresult',
            name='last_updt_dtm',
            field=models.CharField(blank=True, max_length=50, verbose_name='최종수정일시'),
        ),
        migrations.AlterField(
            model_name='regulatorynews',
            name='collected_date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='수집일'),
        ),
        migrations.AddField(
            model_name='inspectionmatch',
            name='fcm_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='NULL = FCM 미발송 (배치 발송 대기 중)', null=True, verbose_name='FCM 발송일시'),
        ),
        migrations.AlterField(
            model_name='inspectionmatch',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='NULL = 아직 처리 전', null=True, verbose_name='알림 생성일시'),
        ),
    ]
