# Generated by Django 5.2.17 on 2026-09-09 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0004_alter_inspectionresult_tkawyprno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('keyword', '부적합 키워드'), ('ingredient', '내 원료·제품명'), ('company', '업체명')], db_index=True, max_length=20, verbose_name='제외 기준')),
                ('value', models.CharField(help_text='사용자에게 보여 줄 원래 표기', max_length=200, verbose_name='제외 값')),
                ('value_norm', models.CharField(db_index=True, help_text='공백 제거 + 소문자. 중복 방지와 조회에 쓴다', max_length=200, verbose_name='비교용 정규화 값')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='끈 이유')),
                ('hidden_count', models.IntegerField(default=0, help_text='끌 때 함께 숨긴 기존 매칭 건수', verbose_name='정리한 기존 알림 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_mutes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림 제외 규칙',
                'verbose_name_plural': '알림 제외 규칙 목록',
                'db_table': 'regulatory_alert_mute',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'scope'], name='regulatory__user_id_0f9888_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'scope', 'value_norm'), name='uniq_alert_mute_user_scope_value')],
            },
        ),
    ]
