# Generated by Django 5.2.17 on 2026-09-10 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_initial'),
        ('regulatory', '0005_alertmute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsKeywordMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_keyword', models.CharField(max_length=100, verbose_name='매칭 키워드')),
                ('category', models.CharField(blank=True, default='', help_text='INGREDIENT / COMPANY / ORIGIN', max_length=20, verbose_name='키워드 분류')),
                ('match_type', models.CharField(blank=True, default='', help_text='EXACT / CONTAINS', max_length=20, verbose_name='매칭 방식')),
                ('read_yn', models.BooleanField(db_index=True, default=False, verbose_name='확인 여부')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 일시')),
                ('dismissed_yn', models.BooleanField(db_index=True, default=False, verbose_name='해당 없음')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_matches', to='regulatory.regulatorynews', verbose_name='부적합 정보')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_matches', to='mobile.alertrule', verbose_name='알림 키워드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_news_matches', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '부적합-키워드 연결',
                'verbose_name_plural': '부적합-키워드 연결 목록',
                'db_table': 'regulatory_news_keyword_match',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_yn'], name='regulatory__user_id_90433b_idx')],
                'unique_together': {('news', 'user', 'rule')},
            },
        ),
    ]
