# Generated by Django 5.1.4 on 2026-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0005_inspectionmatch_fcm_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresult',
            name='tkawyprno',
            field=models.CharField(max_length=50, verbose_name='수거증번호'),
        ),
        migrations.AddConstraint(
            model_name='inspectionresult',
            constraint=models.UniqueConstraint(fields=('tkawydtm', 'bssh_nm', 'prdlst_report_no', 'tkawyprno'), name='uniq_inspection_result_dedup_key'),
        ),
    ]
