# Generated by Django 5.1.6 on 2026-05-02 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriculturalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lclas_nm",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="대분류"
                    ),
                ),
                (
                    "mlsfc_nm",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="중분류"
                    ),
                ),
                (
                    "rprsnt_rawmtrl_nm",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="명칭"
                    ),
                ),
                (
                    "rawmtrl_ncknm",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="이명"
                    ),
                ),
                (
                    "eng_nm",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="영문명"
                    ),
                ),
                ("scnm", models.TextField(blank=True, null=True, verbose_name="학명")),
                (
                    "regn_cd_nm",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="부위명"
                    ),
                ),
                (
                    "rawmtrl_stats_cd_nm",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="상태명"
                    ),
                ),
                (
                    "use_cnd_nm",
                    models.TextField(blank=True, null=True, verbose_name="사용 조건"),
                ),
            ],
            options={
                "db_table": "agricultural_product",
                "indexes": [
                    models.Index(
                        fields=["rprsnt_rawmtrl_nm"], name="idx_rprsnt_rawmtrl_nm"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CountryList",
            fields=[
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        verbose_name="국가코드 alpha3",
                    ),
                ),
                (
                    "country_code2",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="국가코드 alpha2",
                    ),
                ),
                (
                    "numeric_code",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        verbose_name="국가코드 숫자",
                    ),
                ),
                (
                    "country_name_en",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="영문 국가명"
                    ),
                ),
                (
                    "country_name_ko",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="한글 국가명"
                    ),
                ),
            ],
            options={
                "db_table": "country_list",
                "indexes": [
                    models.Index(fields=["country_code2"], name="idx_country_code2")
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpiryRecommendation",
            fields=[
                (
                    "food_type",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="식품유형",
                    ),
                ),
                (
                    "shelf_life",
                    models.CharField(
                        help_text="숫자 또는 '제품별'",
                        max_length=10,
                        verbose_name="권장 소비기한",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="months, days 등",
                        max_length=10,
                        null=True,
                        verbose_name="단위",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "소비기한 권장정보",
                "verbose_name_plural": "소비기한 권장정보",
                "db_table": "expiry_recommendation",
                "indexes": [
                    models.Index(fields=["food_type"], name="idx_expiry_food_type")
                ],
            },
        ),
        migrations.CreateModel(
            name="FoodAdditive",
            fields=[
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="식품첨가물 대분류"),
                ),
                (
                    "name_kr",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="식품첨가물 명칭(한글)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="영문명"
                    ),
                ),
                (
                    "alias_name",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="이명"
                    ),
                ),
                (
                    "ins_no",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="INS No."
                    ),
                ),
                (
                    "e_no",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="E No."
                    ),
                ),
                (
                    "cas_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="CAS No."
                    ),
                ),
                (
                    "alias_4",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="표4 명칭+용도",
                    ),
                ),
                (
                    "alias_5",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="표5 명칭 또는 간략명",
                    ),
                ),
                (
                    "alias_6",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="표6 명칭 또는 간략명 또는 용도",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="간략명"
                    ),
                ),
                (
                    "main_purpose",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="주용도"
                    ),
                ),
                (
                    "color_agent",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="착색료"
                    ),
                ),
                (
                    "sweetener",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="감미료"
                    ),
                ),
                (
                    "nutrient_enhancer",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="영양강화제"
                    ),
                ),
                (
                    "preservative",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="보존료"
                    ),
                ),
                (
                    "antioxidant",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="산화방지제"
                    ),
                ),
                (
                    "bleaching_agent",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="표백제"
                    ),
                ),
                (
                    "color_fixative",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="발색제"
                    ),
                ),
                (
                    "stabilizer",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="안정제"
                    ),
                ),
                (
                    "emulsifier",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="유화제"
                    ),
                ),
                (
                    "thickener",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="증점제"
                    ),
                ),
                (
                    "coagulant",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="응고제"
                    ),
                ),
                (
                    "leavening_agent",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="팽창제"
                    ),
                ),
                (
                    "sterilizer",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="살균제"
                    ),
                ),
                (
                    "coating_agent",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="피막제"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
            ],
            options={
                "db_table": "food_additives",
                "indexes": [
                    models.Index(fields=["name_kr"], name="idx_foodadditive_name_kr")
                ],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "lcns_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="영업에 대한 허가, 등록, 신고번호 11자리",
                        max_length=11,
                        null=True,
                        verbose_name="인허가번호",
                    ),
                ),
                (
                    "bssh_nm",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="제조사명",
                    ),
                ),
                (
                    "prdlst_report_no",
                    models.CharField(
                        db_index=True,
                        help_text="영업등록 발급연도-영업장 등록번호-영업장 제품번호",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="품목보고번호",
                    ),
                ),
                (
                    "prms_dt",
                    models.CharField(
                        db_index=True,
                        default="",
                        help_text="yyyymmdd",
                        max_length=8,
                        verbose_name="허가일자",
                    ),
                ),
                (
                    "prdlst_nm",
                    models.CharField(
                        db_index=True, default="", max_length=200, verbose_name="제품명"
                    ),
                ),
                (
                    "prdlst_dcnm",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="품목유형명",
                    ),
                ),
                (
                    "production",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="생산종료여부",
                    ),
                ),
                (
                    "hieng_lntrt_dvs_yn",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="고열량저영양식품여부",
                    ),
                ),
                (
                    "child_crtfc_yn",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="어린이기호식품품질인증여부",
                    ),
                ),
                (
                    "pog_daycnt",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        verbose_name="소비기한",
                    ),
                ),
                (
                    "last_updt_dtm",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="최종수정일자"
                    ),
                ),
                (
                    "induty_cd_nm",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="업종명"
                    ),
                ),
                (
                    "qlity_mntnc_tmlmt_daycnt",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="품질유지기한일수",
                    ),
                ),
                (
                    "usages",
                    models.TextField(
                        blank=True, max_length=4000, null=True, verbose_name="용법"
                    ),
                ),
                (
                    "prpos",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="용도"
                    ),
                ),
                (
                    "dispos",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="제품형태"
                    ),
                ),
                (
                    "frmlc_mtrqlt",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="포장재질"
                    ),
                ),
                (
                    "rawmtrl_nm",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="원재료명"
                    ),
                ),
                (
                    "rawmtrl_ordno",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="원재료순서",
                    ),
                ),
                (
                    "rawmtrl_nm_sorted",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="원재료명 정렬",
                    ),
                ),
                ("update_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "food_item",
                "indexes": [
                    models.Index(fields=["lcns_no"], name="idx_lcns_no"),
                    models.Index(
                        fields=["prdlst_report_no"], name="idx_prdlst_report_no"
                    ),
                    models.Index(fields=["prdlst_nm"], name="idx_prdlst_nm"),
                    models.Index(fields=["last_updt_dtm"], name="idx_last_updt_dtm"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FoodType",
            fields=[
                (
                    "food_group",
                    models.CharField(
                        default="default_group", max_length=100, verbose_name="식품군"
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        default="default_food_type",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="식품유형",
                    ),
                ),
                (
                    "prdlst_dcnm",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="식품유형명"
                    ),
                ),
                (
                    "weight_calorie",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="내용량(열량)",
                    ),
                ),
                (
                    "prdlst_report_no",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="품목보고번호",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="원산지"
                    ),
                ),
                (
                    "frmlc_mtrqlt",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="포장재질"
                    ),
                ),
                (
                    "pog_daycnt",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="소비기한"
                    ),
                ),
                (
                    "rawmtrl_nm",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="원재료명"
                    ),
                ),
                (
                    "storage_method",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="보관방법"
                    ),
                ),
                (
                    "nutritions",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="영양성분"
                    ),
                ),
                (
                    "cautions",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="주의사항"
                    ),
                ),
                (
                    "type_check",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="구분"
                    ),
                ),
                (
                    "relevant_regulations",
                    models.TextField(
                        blank=True, null=True, verbose_name="식품유형별 관련규정"
                    ),
                ),
            ],
            options={
                "db_table": "food_type",
                "indexes": [models.Index(fields=["food_type"], name="idx_food_type")],
            },
        ),
        migrations.CreateModel(
            name="ImportedFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dcl_prduct_se_cd_nm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="제품구분"
                    ),
                ),
                (
                    "bsn_ofc_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="수입업체명"
                    ),
                ),
                (
                    "prduct_korean_nm",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="제품명(한글)"
                    ),
                ),
                (
                    "prduct_nm",
                    models.TextField(
                        blank=True, null=True, verbose_name="제품명(영문)"
                    ),
                ),
                (
                    "expirde_dtm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="yyyymmdd",
                        max_length=50,
                        null=True,
                        verbose_name="유통기한",
                    ),
                ),
                (
                    "procs_dtm",
                    models.CharField(
                        blank=True,
                        help_text="yyyymmdd",
                        max_length=8,
                        null=True,
                        verbose_name="수입신고일자",
                    ),
                ),
                (
                    "ovsmnfst_nm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=500,
                        null=True,
                        verbose_name="해외제조업소",
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="품목",
                    ),
                ),
                (
                    "xport_ntncd_nm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="수출국",
                    ),
                ),
                (
                    "mnf_ntncn_nm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="제조국"
                    ),
                ),
                (
                    "korlabel",
                    models.TextField(
                        blank=True, null=True, verbose_name="한글표시사항"
                    ),
                ),
                (
                    "irdnt_nm",
                    models.TextField(blank=True, null=True, verbose_name="원재료명"),
                ),
                (
                    "expirde_bdgin_dtm",
                    models.CharField(
                        blank=True,
                        help_text="yyyymmdd",
                        max_length=8,
                        null=True,
                        verbose_name="유통기한",
                    ),
                ),
                (
                    "expirde_end_dtm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="yyyymmdd",
                        max_length=8,
                        null=True,
                        verbose_name="소비기한",
                    ),
                ),
            ],
            options={
                "db_table": "imported_food",
                "indexes": [
                    models.Index(fields=["bsn_ofc_name"], name="idx_bsn_ofc_name"),
                    models.Index(fields=["itm_nm"], name="idx_itm_nm"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MyIngredient",
            fields=[
                (
                    "my_ingredient_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "prdlst_report_no",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="품목보고번호",
                    ),
                ),
                (
                    "prdlst_nm",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="원료명"
                    ),
                ),
                (
                    "bssh_nm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="제조사명"
                    ),
                ),
                (
                    "prms_dt",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="허가일자"
                    ),
                ),
                (
                    "food_category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="식품구분"
                    ),
                ),
                (
                    "prdlst_dcnm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="식품유형"
                    ),
                ),
                (
                    "pog_daycnt",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="소비기한"
                    ),
                ),
                (
                    "frmlc_mtrqlt",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="포장재질"
                    ),
                ),
                (
                    "rawmtrl_nm",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="하위 원료"
                    ),
                ),
                (
                    "induty_cd_nm",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="업종명"
                    ),
                ),
                (
                    "hieng_lntrt_dvs_yn",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="고열량저영양식품여부",
                    ),
                ),
                (
                    "ingredient_display_name",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="원료 표시명",
                    ),
                ),
                (
                    "summary_type_flag",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="요약 타입"
                    ),
                ),
                (
                    "allergens",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="알레르기 물질",
                    ),
                ),
                (
                    "gmo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="GMO"
                    ),
                ),
                ("update_datetime", models.DateTimeField(auto_now=True)),
                (
                    "delete_datetime",
                    models.CharField(
                        default="",
                        help_text="yyyymmdd",
                        max_length=8,
                        verbose_name="삭제일자",
                    ),
                ),
                (
                    "delete_YN",
                    models.CharField(max_length=1, verbose_name="내 제품 삭제 여부"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ingredient",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자 id",
                    ),
                ),
            ],
            options={
                "db_table": "my_ingredient",
            },
        ),
        migrations.CreateModel(
            name="LabelIngredientRelation",
            fields=[
                (
                    "relation_id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ingredient_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="원료 비율(%)",
                    ),
                ),
                (
                    "relation_sequence",
                    models.IntegerField(default=1, verbose_name="원재료 순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_relations",
                        to="label.myingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "라벨-원료 관계",
                "verbose_name_plural": "라벨-원료 관계들",
                "db_table": "label_ingredient_relation",
                "ordering": ["ingredient_ratio"],
            },
        ),
        migrations.CreateModel(
            name="MyLabel",
            fields=[
                ("my_label_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "food_group",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="식품 대분류",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="식품 소분류",
                    ),
                ),
                (
                    "preservation_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="장기보존식품",
                    ),
                ),
                (
                    "processing_method",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="제조방법"
                    ),
                ),
                (
                    "processing_condition",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="제조방법 조건",
                    ),
                ),
                (
                    "my_label_name",
                    models.CharField(max_length=200, verbose_name="라벨명"),
                ),
                (
                    "prdlst_dcnm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="식품유형"
                    ),
                ),
                (
                    "prdlst_nm",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="제품명"
                    ),
                ),
                (
                    "ingredient_info",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="특정성분 함량",
                    ),
                ),
                (
                    "content_weight",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="내용량"
                    ),
                ),
                (
                    "weight_calorie",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="내용량(열량)",
                    ),
                ),
                (
                    "prdlst_report_no",
                    models.TextField(
                        blank=True, null=True, verbose_name="품목보고번호"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="원산지"
                    ),
                ),
                (
                    "storage_method",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="보관방법"
                    ),
                ),
                (
                    "frmlc_mtrqlt",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="포장재질"
                    ),
                ),
                (
                    "bssh_nm",
                    models.TextField(
                        blank=True, null=True, verbose_name="제조원 소재지"
                    ),
                ),
                (
                    "distributor_address",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="유통전문판매원 소재지",
                    ),
                ),
                (
                    "repacker_address",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="소분원 소재지",
                    ),
                ),
                (
                    "importer_address",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="수입원 소재지",
                    ),
                ),
                (
                    "pog_daycnt",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="소비기한"
                    ),
                ),
                (
                    "rawmtrl_nm",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="원재료명"
                    ),
                ),
                (
                    "rawmtrl_nm_display",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="원재료명(표시)",
                    ),
                ),
                (
                    "cautions",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="주의사항"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="기타 표시사항",
                    ),
                ),
                (
                    "nutrition_text",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="영양성분 표시",
                    ),
                ),
                (
                    "serving_size",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="단위 내용량"
                    ),
                ),
                (
                    "serving_size_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="단위 내용량 단위",
                    ),
                ),
                (
                    "units_per_package",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="포장 당 갯수",
                    ),
                ),
                (
                    "nutrition_display_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="영양성분 표시 단위",
                    ),
                ),
                (
                    "basic_display_type",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="기본형 표시 기준",
                    ),
                ),
                (
                    "parallel_display_type",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="병렬형 표시 기준",
                    ),
                ),
                (
                    "calories",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="칼로리"
                    ),
                ),
                (
                    "calories_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="칼로리 단위"
                    ),
                ),
                (
                    "natriums",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="나트륨"
                    ),
                ),
                (
                    "natriums_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="나트륨 단위"
                    ),
                ),
                (
                    "carbohydrates",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="탄수화물"
                    ),
                ),
                (
                    "carbohydrates_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="탄수화물 단위",
                    ),
                ),
                (
                    "sugars",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="당류"
                    ),
                ),
                (
                    "sugars_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="당류 단위"
                    ),
                ),
                (
                    "fats",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="지방"
                    ),
                ),
                (
                    "fats_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="지방 단위"
                    ),
                ),
                (
                    "trans_fats",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="트랜스지방"
                    ),
                ),
                (
                    "trans_fats_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="트랜스지방 단위",
                    ),
                ),
                (
                    "saturated_fats",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="포화지방"
                    ),
                ),
                (
                    "saturated_fats_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="포화지방 단위",
                    ),
                ),
                (
                    "cholesterols",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="콜레스테롤"
                    ),
                ),
                (
                    "cholesterols_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="콜레스테롤 단위",
                    ),
                ),
                (
                    "proteins",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="단백질"
                    ),
                ),
                (
                    "proteins_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="단백질 단위"
                    ),
                ),
                (
                    "dietary_fiber",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="식이섬유"
                    ),
                ),
                (
                    "dietary_fiber_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="식이섬유 단위",
                    ),
                ),
                (
                    "calcium",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="칼슘"
                    ),
                ),
                (
                    "calcium_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="칼슘 단위"
                    ),
                ),
                (
                    "iron",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="철"
                    ),
                ),
                (
                    "iron_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="철 단위"
                    ),
                ),
                (
                    "magnesium",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="마그네슘"
                    ),
                ),
                (
                    "magnesium_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="마그네슘 단위",
                    ),
                ),
                (
                    "phosphorus",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="인"
                    ),
                ),
                (
                    "phosphorus_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="인 단위"
                    ),
                ),
                (
                    "potassium",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="칼륨"
                    ),
                ),
                (
                    "potassium_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="칼륨 단위"
                    ),
                ),
                (
                    "zinc",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="아연"
                    ),
                ),
                (
                    "zinc_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="아연 단위"
                    ),
                ),
                (
                    "vitamin_a",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="비타민A"
                    ),
                ),
                (
                    "vitamin_a_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="비타민A 단위",
                    ),
                ),
                (
                    "vitamin_d",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="비타민D"
                    ),
                ),
                (
                    "vitamin_d_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="비타민D 단위",
                    ),
                ),
                (
                    "vitamin_c",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="비타민C"
                    ),
                ),
                (
                    "vitamin_c_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="비타민C 단위",
                    ),
                ),
                (
                    "thiamine",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="티아민"
                    ),
                ),
                (
                    "thiamine_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="티아민 단위"
                    ),
                ),
                (
                    "riboflavin",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="리보플라빈"
                    ),
                ),
                (
                    "riboflavin_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="리보플라빈 단위",
                    ),
                ),
                (
                    "niacin",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="니아신"
                    ),
                ),
                (
                    "niacin_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="니아신 단위"
                    ),
                ),
                (
                    "vitamin_b6",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="비타민B6"
                    ),
                ),
                (
                    "vitamin_b6_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="비타민B6 단위",
                    ),
                ),
                (
                    "folic_acid",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="엽산"
                    ),
                ),
                (
                    "folic_acid_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="엽산 단위"
                    ),
                ),
                (
                    "vitamin_b12",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="비타민B12"
                    ),
                ),
                (
                    "vitamin_b12_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="비타민B12 단위",
                    ),
                ),
                (
                    "selenium",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="셀레늄"
                    ),
                ),
                (
                    "selenium_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="셀레늄 단위"
                    ),
                ),
                (
                    "iodine",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="요오드"
                    ),
                ),
                (
                    "iodine_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="요오드 단위"
                    ),
                ),
                (
                    "copper",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="구리"
                    ),
                ),
                (
                    "copper_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="구리 단위"
                    ),
                ),
                (
                    "manganese",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="망간"
                    ),
                ),
                (
                    "manganese_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="망간 단위"
                    ),
                ),
                (
                    "chromium",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="크롬"
                    ),
                ),
                (
                    "chromium_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="크롬 단위"
                    ),
                ),
                (
                    "molybdenum",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="몰리브덴"
                    ),
                ),
                (
                    "molybdenum_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="몰리브덴 단위",
                    ),
                ),
                (
                    "vitamin_e",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="비타민E"
                    ),
                ),
                (
                    "vitamin_e_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="비타민E 단위",
                    ),
                ),
                (
                    "vitamin_k",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="비타민K"
                    ),
                ),
                (
                    "vitamin_k_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="비타민K 단위",
                    ),
                ),
                (
                    "biotin",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="바이오틴"
                    ),
                ),
                (
                    "biotin_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="바이오틴 단위",
                    ),
                ),
                (
                    "pantothenic_acid",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="판토텐산"
                    ),
                ),
                (
                    "pantothenic_acid_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="판토텐산 단위",
                    ),
                ),
                (
                    "allergens",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="알레르기 물질",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="맞춤항목"
                    ),
                ),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("update_datetime", models.DateTimeField(auto_now=True)),
                (
                    "label_create_YN",
                    models.CharField(
                        default="N", max_length=1, verbose_name="표시사항 작성여부"
                    ),
                ),
                (
                    "report_no_verify_YN",
                    models.CharField(
                        default="N", max_length=1, verbose_name="품목보고번호 검증 여부"
                    ),
                ),
                (
                    "delete_datetime",
                    models.CharField(
                        default="",
                        help_text="yyyymmdd",
                        max_length=8,
                        verbose_name="삭제일자",
                    ),
                ),
                (
                    "delete_YN",
                    models.CharField(
                        default="N", max_length=1, verbose_name="표시사항 삭제 여부"
                    ),
                ),
                (
                    "chckd_prdlst_dcnm",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="식품유형 체크"
                    ),
                ),
                (
                    "chckd_prdlst_nm",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="제품명 체크"
                    ),
                ),
                (
                    "chckd_ingredient_info",
                    models.CharField(
                        default="N", max_length=1, verbose_name="특정성분 함량 체크"
                    ),
                ),
                (
                    "chckd_content_weight",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="내용량 체크"
                    ),
                ),
                (
                    "chckd_weight_calorie",
                    models.CharField(
                        default="N", max_length=1, verbose_name="내용량(열량) 체크"
                    ),
                ),
                (
                    "chckd_prdlst_report_no",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="품목보고번호 체크"
                    ),
                ),
                (
                    "chckd_country_of_origin",
                    models.CharField(
                        default="N", max_length=1, verbose_name="원산지 체크"
                    ),
                ),
                (
                    "chckd_storage_method",
                    models.CharField(
                        default="N", max_length=1, verbose_name="보관방법 체크"
                    ),
                ),
                (
                    "chckd_frmlc_mtrqlt",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="용기.포장재질 체크"
                    ),
                ),
                (
                    "chckd_bssh_nm",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="제조원 소재지 체크"
                    ),
                ),
                (
                    "chckd_distributor_address",
                    models.CharField(
                        default="N", max_length=1, verbose_name="유통전문판매원 체크"
                    ),
                ),
                (
                    "chckd_repacker_address",
                    models.CharField(
                        default="N", max_length=1, verbose_name="소분원 체크"
                    ),
                ),
                (
                    "chckd_importer_address",
                    models.CharField(
                        default="N", max_length=1, verbose_name="수입원 체크"
                    ),
                ),
                (
                    "chckd_pog_daycnt",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="소비기한 체크"
                    ),
                ),
                (
                    "chckd_rawmtrl_nm_display",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="원재료명(표시) 체크"
                    ),
                ),
                (
                    "chckd_cautions",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="주의사항 체크"
                    ),
                ),
                (
                    "chckd_additional_info",
                    models.CharField(
                        default="N", max_length=1, verbose_name="기타표시사항 체크"
                    ),
                ),
                (
                    "chckd_nutrition_text",
                    models.CharField(
                        default="N", max_length=1, verbose_name="영양성분 체크"
                    ),
                ),
                (
                    "prv_layout",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="레이아웃"
                    ),
                ),
                (
                    "prv_width",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="가로"
                    ),
                ),
                (
                    "prv_length",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="세로"
                    ),
                ),
                (
                    "prv_font",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="글꼴"
                    ),
                ),
                (
                    "prv_font_size",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="글꼴 크기"
                    ),
                ),
                (
                    "prv_letter_spacing",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="자간"
                    ),
                ),
                (
                    "prv_line_spacing",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="행간"
                    ),
                ),
                (
                    "prv_recycling_mark_enabled",
                    models.CharField(
                        blank=True,
                        default="N",
                        max_length=1,
                        null=True,
                        verbose_name="분리배출마크 적용여부",
                    ),
                ),
                (
                    "prv_recycling_mark_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="분리배출마크 종류",
                    ),
                ),
                (
                    "prv_recycling_mark_position_x",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="분리배출마크 X좌표",
                    ),
                ),
                (
                    "prv_recycling_mark_position_y",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="분리배출마크 Y좌표",
                    ),
                ),
                (
                    "prv_recycling_mark_text",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="분리배출마크 추가텍스트",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        related_name="labels",
                        through="label.LabelIngredientRelation",
                        to="label.myingredient",
                        verbose_name="연결된 원재료",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_label",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자 id",
                    ),
                ),
            ],
            options={
                "db_table": "my_label",
            },
        ),
        migrations.AddField(
            model_name="labelingredientrelation",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_relations",
                to="label.mylabel",
            ),
        ),
        migrations.CreateModel(
            name="MyPhrase",
            fields=[
                ("my_phrase_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "my_phrase_name",
                    models.CharField(max_length=200, verbose_name="내 문구명"),
                ),
                (
                    "category_name",
                    models.CharField(
                        choices=[
                            ("product_name", "제품명"),
                            ("ingredient_info", "특정 성분 함량"),
                            ("food_type", "식품유형"),
                            ("report_no", "품목보고번호"),
                            ("content_weight", "내용량"),
                            ("storage", "보관방법"),
                            ("package", "용기.포장재질"),
                            ("manufacturer", "제조원 소재지"),
                            ("distributor", "유통전문판매원"),
                            ("repacker", "소분원"),
                            ("importer", "수입원"),
                            ("expiry", "소비기한"),
                            ("cautions", "주의사항"),
                            ("additional", "기타표시사항"),
                        ],
                        max_length=100,
                        verbose_name="문구 카테고리",
                    ),
                ),
                (
                    "comment_content",
                    models.TextField(max_length=1000, verbose_name="문구 내용"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="사용조건"
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "delete_datetime",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="yyyymmdd",
                        max_length=8,
                        verbose_name="삭제일자",
                    ),
                ),
                (
                    "delete_YN",
                    models.CharField(
                        default="N", max_length=1, verbose_name="삭제 여부"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_phrase",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자 id",
                    ),
                ),
            ],
            options={
                "db_table": "my_comment_storage",
                "ordering": ["display_order", "-update_datetime"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="labelingredientrelation",
            unique_together={("label", "ingredient")},
        ),
    ]
