# Generated by Django 5.2.17 on 2026-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0020_remove_fooditem_idx_lcns_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylabel',
            name='ingredients',
            field=models.ManyToManyField(related_name='labels', through='label.LabelIngredientRelation', through_fields=('label', 'ingredient'), to='label.myingredient', verbose_name='연결된 원재료'),
        ),
    ]
