# Generated by Django 5.2.17 on 2026-09-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0021_alter_mylabel_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='prv_field_layout',
            field=models.JSONField(blank=True, null=True, verbose_name='표 항목 배치'),
        ),
    ]
