# Generated by Django 5.2.17 on 2026-09-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0023_display_check_matches_printed_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='hieng_kind',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='고열량저영양 판정 구분'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='nutrition_source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='영양성분 산출 방법'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='nutrition_source_note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='영양성분 산출 근거'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='nutrition_tolerance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='적용한 허용오차(%)'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='serving_reference',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='1회 섭취참고량'),
        ),
    ]
