# Generated by Django 5.2.17 on 2026-09-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0024_mylabel_hieng_kind_mylabel_nutrition_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='nutrition_calc_values',
            field=models.TextField(blank=True, null=True, verbose_name='영양성분 계산값(JSON)'),
        ),
    ]
