# Generated by Django 5.2.17 on 2026-09-08 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0025_mylabel_nutrition_calc_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('RED', '위험 — 사용 불가'), ('YELLOW', '조건부 — 근거 확보 시 가능'), ('GREEN', '사용 가능')], db_index=True, default='RED', max_length=6, verbose_name='등급')),
                ('keyword', models.CharField(help_text='사람이 읽는 이름. 화면에 이 이름이 나옵니다.', max_length=100, verbose_name='키워드')),
                ('match_strings', models.CharField(help_text='문구에서 실제로 찾을 말. 여러 개면 · 로 구분합니다. 비워 두면 키워드를 그대로 찾습니다.', max_length=500, verbose_name='매칭 문자열')),
                ('note', models.TextField(blank=True, default='', help_text='조건부(YELLOW)일 때 무엇을 갖춰야 하는지. 화면에 그대로 보여 줍니다.', verbose_name='비고')),
                ('active_yn', models.BooleanField(db_index=True, default=True, verbose_name='사용')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('owner', models.ForeignKey(blank=True, help_text='비워 두면 모든 사용자에게 적용되는 공용 기본입니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_keywords', to=settings.AUTH_USER_MODEL, verbose_name='사내 기준 소유자')),
            ],
            options={
                'verbose_name': '부당표시 키워드',
                'verbose_name_plural': '부당표시 키워드',
                'db_table': 'label_ad_keyword',
                'ordering': ['grade', 'keyword'],
                'indexes': [models.Index(fields=['owner', 'active_yn'], name='label_ad_ke_owner_i_cd22b0_idx')],
            },
        ),
    ]
