# Generated by Django 5.2.17 on 2026-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0026_adkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='package_form',
            field=models.CharField(blank=True, help_text='주표시면·정보표시면이 어디인지를 정한다', max_length=20, null=True, verbose_name='포장 형태'),
        ),
    ]
