# Generated by Django 5.2.17 on 2026-09-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0027_mylabel_package_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_cd', models.CharField(max_length=40, unique=True, verbose_name='식품코드')),
                ('food_nm_kr', models.CharField(db_index=True, max_length=300, verbose_name='식품명')),
                ('db_grp_nm', models.CharField(blank=True, db_index=True, help_text='가공식품 / 음식 / 원재료성', max_length=30, null=True, verbose_name='데이터구분명')),
                ('db_class_nm', models.CharField(blank=True, max_length=30, null=True, verbose_name='품목대표·상용제품')),
                ('food_cat1_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='식품대분류명')),
                ('item_report_no', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='품목제조보고번호')),
                ('maker_nm', models.CharField(blank=True, max_length=200, null=True, verbose_name='업체명')),
                ('imp_yn', models.CharField(blank=True, max_length=10, null=True, verbose_name='수입여부')),
                ('nation_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='원산지국명')),
                ('basis_amount', models.FloatField(blank=True, null=True, verbose_name='기준량')),
                ('basis_unit', models.CharField(blank=True, choices=[('g', '100g 기준'), ('mL', '100mL 기준')], help_text='비면 원본 기준량을 읽지 못한 행', max_length=5, null=True, verbose_name='기준 단위')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='에너지(kcal)')),
                ('proteins', models.FloatField(blank=True, null=True, verbose_name='단백질(g)')),
                ('fats', models.FloatField(blank=True, null=True, verbose_name='지방(g)')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)')),
                ('sugars', models.FloatField(blank=True, null=True, verbose_name='당류(g)')),
                ('dietary_fiber', models.FloatField(blank=True, null=True, verbose_name='식이섬유(g)')),
                ('sugar_alcohols', models.FloatField(blank=True, null=True, verbose_name='당알콜(g)')),
                ('natriums', models.FloatField(blank=True, null=True, verbose_name='나트륨(mg)')),
                ('cholesterols', models.FloatField(blank=True, null=True, verbose_name='콜레스테롤(mg)')),
                ('saturated_fats', models.FloatField(blank=True, null=True, verbose_name='포화지방산(g)')),
                ('trans_fats', models.FloatField(blank=True, null=True, verbose_name='트랜스지방산(g)')),
                ('calcium', models.FloatField(blank=True, null=True, verbose_name='칼슘(mg)')),
                ('iron', models.FloatField(blank=True, null=True, verbose_name='철(mg)')),
                ('phosphorus', models.FloatField(blank=True, null=True, verbose_name='인(mg)')),
                ('potassium', models.FloatField(blank=True, null=True, verbose_name='칼륨(mg)')),
                ('magnesium', models.FloatField(blank=True, null=True, verbose_name='마그네슘(mg)')),
                ('selenium', models.FloatField(blank=True, null=True, verbose_name='셀레늄(μg)')),
                ('zinc', models.FloatField(blank=True, null=True, verbose_name='아연(mg)')),
                ('moisture', models.FloatField(blank=True, help_text='수율 검산의 근거 — 표시 성분은 아니다', null=True, verbose_name='수분(g)')),
                ('ash', models.FloatField(blank=True, null=True, verbose_name='회분(g)')),
                ('refuse_rate', models.FloatField(blank=True, null=True, verbose_name='폐기율(%)')),
                ('crt_mth_nm', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='데이터생성방법명')),
                ('sub_ref_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='출처명')),
                ('research_ymd', models.CharField(blank=True, help_text='"3년 경과" 같은 오래됨 경고에 쓴다', max_length=20, null=True, verbose_name='데이터생성일자')),
                ('update_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='데이터수정일자')),
                ('verify_status', models.CharField(choices=[('pass', '검산 통과'), ('fail', '검산 어긋남'), ('skip', '잴 수 없음')], db_index=True, default='skip', max_length=10, verbose_name='검산 결과')),
                ('verify_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='검산 사유')),
                ('raw', models.JSONField(blank=True, help_text='꺼내지 않은 성분 130여 종이 여기 남아 있다', null=True, verbose_name='원문')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='적재일시')),
            ],
            options={
                'verbose_name': '식약처 영양성분',
                'verbose_name_plural': '식약처 영양성분',
                'db_table': 'public_food_nutrition',
                'indexes': [models.Index(fields=['db_grp_nm', 'verify_status'], name='public_food_db_grp__ec4dc6_idx')],
            },
        ),
    ]
