# Generated by Django 5.2.17 on 2026-09-10 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0028_publicfoodnutrition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyIngredientNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('spec_ocr', '업체 시험성적서'), ('report_no', '품목보고번호 일치'), ('picked', '식약처DB에서 고름'), ('manual', '직접 입력'), ('negligible', '영향 없음으로 확정')], db_index=True, default='manual', max_length=20, verbose_name='값의 출처')),
                ('source_note', models.CharField(blank=True, help_text='성적서 번호·발급일 등', max_length=300, null=True, verbose_name='근거')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='고른 때')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='열량(kcal)')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)')),
                ('sugars', models.FloatField(blank=True, null=True, verbose_name='당류(g)')),
                ('proteins', models.FloatField(blank=True, null=True, verbose_name='단백질(g)')),
                ('fats', models.FloatField(blank=True, null=True, verbose_name='지방(g)')),
                ('saturated_fats', models.FloatField(blank=True, null=True, verbose_name='포화지방(g)')),
                ('trans_fats', models.FloatField(blank=True, null=True, verbose_name='트랜스지방(g)')),
                ('cholesterols', models.FloatField(blank=True, null=True, verbose_name='콜레스테롤(mg)')),
                ('natriums', models.FloatField(blank=True, null=True, verbose_name='나트륨(mg)')),
                ('dietary_fiber', models.FloatField(blank=True, null=True, verbose_name='식이섬유(g)')),
                ('sugar_alcohols', models.FloatField(blank=True, null=True, verbose_name='당알콜(g)')),
                ('moisture', models.FloatField(blank=True, help_text='수율 검산에 쓴다 — 표시 성분은 아니다', null=True, verbose_name='수분(g)')),
                ('ash', models.FloatField(blank=True, null=True, verbose_name='회분(g)')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='label.myingredient', verbose_name='원료')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_ingredient_nutritions', to=settings.AUTH_USER_MODEL, verbose_name='고른 사람')),
                ('public_row', models.ForeignKey(blank=True, help_text='값을 베낀 것이 아니라 어느 행을 보았는지를 남긴다', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_by_ingredients', to='label.publicfoodnutrition', verbose_name='본 식약처 행')),
            ],
            options={
                'verbose_name': '내 원료 영양성분',
                'verbose_name_plural': '내 원료 영양성분',
                'db_table': 'my_ingredient_nutrition',
            },
        ),
    ]
