# Generated by Django 5.2.17 on 2026-09-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0029_myingredientnutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicfoodnutrition',
            name='raw',
        ),
    ]
