# Generated by Django 5.2.17 on 2026-09-12 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0030_remove_publicfoodnutrition_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfoodnutrition',
            name='agri_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_rows', to='label.agriculturalproduct', verbose_name='식품원료(A코드)'),
        ),
        migrations.AddField(
            model_name='publicfoodnutrition',
            name='source_db',
            field=models.CharField(blank=True, choices=[('mfds', '식약처 식품영양성분DB'), ('rda', '농진청 국가표준식품성분표')], db_index=True, max_length=10, null=True, verbose_name='출처 DB'),
        ),
    ]
