# Generated by Django 5.2.17 on 2026-09-12 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0031_rda_nutrition_source'),
        ('products', '0008_usercontact_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myingredientnutrition',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_sources', to='products.productdocument', verbose_name='근거 문서'),
        ),
    ]
