# Generated by Django 5.2.17 on 2026-09-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0032_nutrition_source_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='품목보고번호')),
                ('food_name', models.CharField(blank=True, default='', max_length=300, verbose_name='식품명')),
                ('maker_nm', models.CharField(blank=True, default='', max_length=200, verbose_name='업체명')),
                ('food_type', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='식품유형')),
                ('rule_code', models.CharField(db_index=True, max_length=10, verbose_name='규칙')),
                ('severity', models.CharField(choices=[('high', '그럴 수 없음'), ('watch', '봐야 함')], db_index=True, default='watch', max_length=10, verbose_name='심각도')),
                ('detail', models.CharField(max_length=300, verbose_name='무엇이 어긋났나')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='판정일시')),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='label.publicfoodnutrition', verbose_name='영양성분 행')),
            ],
            options={
                'verbose_name': '영양성분 이상 판정',
                'verbose_name_plural': '영양성분 이상 판정',
                'db_table': 'label_nutrition_anomaly',
                'ordering': ['severity', 'rule_code', '-checked_at'],
                'indexes': [models.Index(fields=['rule_code', 'severity'], name='label_nutri_rule_co_5b7ab7_idx'), models.Index(fields=['food_type'], name='label_nutri_food_ty_4410e3_idx')],
            },
        ),
    ]
