# Generated by Django 5.2.17 on 2026-09-18 17:10

# -*- coding: utf-8 -*-
"""
원료에 **표시사항 사진 칸**을 만들고, 제품 문서함에 있던 원료 사진을 걷어낸다.

사진은 원료에 붙어야 한다. ProductDocument.label 은 필수라 사진이 늘 어느 한
제품에 매였고, 같은 크림치즈를 다른 제품에서 쓰면 같은 사진을 또 올려야 했다.

**옛 원료 사진은 지운다.** 이 기능은 만든 지 하루가 안 됐고 쓴 사람이 없다
(사용자 확인). 그대로 두면 사진이 두 군데에 있는 채로 굳는다 — 어느 쪽이
참인지 다음 사람이 알 수 없다. 지금이 가장 싸게 치울 때다.

지우는 방식은 이 저장소의 삭제 규칙을 따른다 — active_yn=False 로 눕힌다.
파일은 그대로 남으므로, 잘못됐다면 그 줄을 다시 세우면 된다.
"""
from django.db import migrations, models


def clear_old_ingredient_photos(apps, schema_editor):
    ProductDocument = apps.get_model('products', 'ProductDocument')
    DocumentType = apps.get_model('products', 'DocumentType')

    codes = list(DocumentType.objects
                 .filter(type_code='INGREDIENT_LABEL')
                 .values_list('type_id', flat=True))
    if not codes:
        return

    docs = ProductDocument.objects.filter(document_type_id__in=codes,
                                          active_yn=True)
    for doc in docs:
        meta = dict(doc.metadata or {})
        # 배합 줄을 가리키던 연결을 끊는다. 남겨 두면 배합표가 없는 사진을
        # 계속 가리킨다.
        meta.pop('ingredient_bom_id', None)
        meta.pop('ingredient_fields', None)
        doc.metadata = meta
        doc.active_yn = False
        doc.save(update_fields=['metadata', 'active_yn'])


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0033_nutrition_anomaly'),
        # 문서 구분을 손대므로 products 가 먼저 서 있어야 한다
        ('products', '0012_document_type_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='myingredient',
            name='label_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient_photos/%Y/%m/', verbose_name='표시사항 사진'),
        ),
        migrations.AddField(
            model_name='myingredient',
            name='label_photo_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='사진에서 읽은 값'),
        ),
        # 되돌리지 않는다. 되살려 봐야 사진이 두 군데 있는 상태로 돌아간다.
        migrations.RunPython(clear_old_ingredient_photos,
                             migrations.RunPython.noop),
    ]
