# Generated by Django 5.1.6 on 2026-03-18 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("label", "표시사항"),
                            ("ingredient", "원료"),
                            ("preview", "미리보기"),
                            ("validation", "검증"),
                            ("search", "조회"),
                            ("calculator", "계산기"),
                            ("board", "게시판"),
                        ],
                        help_text="활동 카테고리",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("label_save", "표시사항 저장"),
                            ("label_create", "표시사항 생성"),
                            ("label_update", "표시사항 수정"),
                            ("label_delete", "표시사항 삭제"),
                            ("label_view", "표시사항 조회"),
                            ("label_copy", "표시사항 복사"),
                            ("label_write", "표시사항 작성"),
                            ("ingredient_save", "원료 저장"),
                            ("ingredient_create", "원료 생성"),
                            ("ingredient_update", "원료 수정"),
                            ("ingredient_delete", "원료 삭제"),
                            ("ingredient_view", "원료 조회"),
                            ("ingredient_link", "원료 연결"),
                            ("ingredient_copy", "원료 복사"),
                            ("calculator_calc", "영양성분 계산"),
                            ("calculator_save", "영양성분 저장"),
                            ("search_domestic", "국내제품 조회"),
                            ("search_import", "수입제품 조회"),
                            ("search_additive", "식품첨가물 조회"),
                            ("search_label_copy", "검색에서 표시사항 복사"),
                            ("search_ingredient_copy", "검색에서 내원료 복사"),
                            ("board_post", "게시글 작성"),
                            ("board_comment", "댓글 작성"),
                            ("validation_report", "품목보고번호 검증"),
                            ("allergen_auto_detect", "알레르기 감지"),
                            ("ingredient_table_input", "원재료 표로 입력"),
                            ("ingredient_quick_register", "원재료 빠른 등록"),
                            ("caution_quick_add", "주의문구 빠른 등록"),
                            ("other_text_quick_add", "기타문구 빠른 등록"),
                            ("custom_field_use", "맞춤항목 등록"),
                            ("mode_switch", "간편/상세 전환"),
                            ("selection_copy", "선택 복사"),
                            ("preview_view", "미리보기 팝업"),
                            ("preview_table_settings", "표 설정"),
                            ("preview_order", "항목 순서"),
                            ("preview_text_transform", "텍스트 변환"),
                            ("preview_recycling_mark", "분리배출마크"),
                            ("validation_nutrition", "규정 검증"),
                            ("preview_pdf_save", "PDF 저장"),
                            ("preview_settings_save", "설정 저장"),
                        ],
                        help_text="수행 액션",
                        max_length=30,
                    ),
                ),
                (
                    "target_id",
                    models.IntegerField(
                        blank=True, help_text="대상 객체 ID", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "common_useractivitylog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"],
                        name="common_user_user_id_b61948_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="common_user_created_038ee9_idx"
                    ),
                    models.Index(
                        fields=["category", "action"],
                        name="common_user_categor_2ba2f3_idx",
                    ),
                ],
            },
        ),
    ]
