# Generated by Django 5.1.4 on 2026-02-21 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False, verbose_name='BOM ID')),
                ('ingredient_name', models.CharField(help_text='표시용 원재료명', max_length=200, verbose_name='원재료명')),
                ('raw_material_name', models.TextField(blank=True, help_text='라벨에 표시될 명칭 (예: 정백당 -> 설탕)', null=True, verbose_name='표시용 원료명')),
                ('sub_ingredients', models.TextField(blank=True, help_text='예: 탈지대두, 소맥, 천일염', null=True, verbose_name='복합원재료 내역')),
                ('allergens', models.CharField(blank=True, help_text='대두, 밀, 우유 등', max_length=255, null=True, verbose_name='알레르기 정보')),
                ('gmo', models.CharField(blank=True, help_text='대두, 옥수수 등 선택된 GMO 성분', max_length=255, null=True, verbose_name='GMO 성분')),
                ('origin_detail', models.CharField(blank=True, help_text='예: 국산 50%, 수입산 50%', max_length=255, null=True, verbose_name='원산지 상세')),
                ('food_type', models.CharField(blank=True, help_text='예: 소스류, 과채가공품', max_length=100, null=True, verbose_name='식품유형')),
                ('is_additive', models.BooleanField(default=False, verbose_name='식품첨가물 여부')),
                ('additive_role', models.CharField(blank=True, help_text='예: 보존료, 착색료', max_length=100, null=True, verbose_name='첨가물 용도')),
                ('is_gmo', models.BooleanField(default=False, verbose_name='GMO 여부')),
                ('report_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='품목보고번호')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='제조사/수입사')),
                ('usage_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='전체 제품 중 이 원료의 함량 비율', max_digits=10, null=True, verbose_name='함량 (%)')),
                ('origin', models.CharField(blank=True, help_text='예: 국내산, 미국산', max_length=200, null=True, verbose_name='원산지')),
                ('allergen', models.CharField(blank=True, help_text='알레르기 유발 물질', max_length=500, null=True, verbose_name='알레르기')),
                ('usage_amount', models.DecimalField(blank=True, decimal_places=4, help_text='실제 사용량 (숫자) - 레거시', max_digits=15, null=True, verbose_name='사용량')),
                ('usage_unit', models.CharField(blank=True, help_text='g, kg, ml, L 등 - 레거시', max_length=20, null=True, verbose_name='사용량 단위')),
                ('level', models.IntegerField(default=1, help_text='1=직접 원료, 2=원료의 원료, ...', verbose_name='레벨')),
                ('sort_order', models.IntegerField(default=0, help_text='같은 레벨 내에서의 순서', verbose_name='정렬 순서')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='비고')),
                ('summary_type', models.CharField(default='식품유형', help_text='원재료 표시명 생성 시 사용할 기준 (식품유형 / 원재료명)', max_length=20, verbose_name='표시명 기준')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('child_label', models.ForeignKey(blank=True, help_text='내가 소유한 표시사항을 원료로 사용', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='label.mylabel', verbose_name='원료 표시사항')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_created_boms', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('parent_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='label.mylabel', verbose_name='완제품 표시사항')),
                ('shared_receipt', models.ForeignKey(blank=True, help_text='공유받은 제품을 원료로 사용', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='products.sharedproductreceipt', verbose_name='공유받은 원료')),
                ('source_ingredient', models.ForeignKey(blank=True, help_text='내 원료 보관함의 원료 (직접 입력 시 자동 생성됨)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_usages', to='label.myingredient', verbose_name='연동 원료')),
            ],
            options={
                'verbose_name': '제품 BOM',
                'verbose_name_plural': '제품 BOM 목록',
                'db_table': 'v2_product_bom',
                'ordering': ['parent_label', 'level', 'sort_order'],
                'indexes': [models.Index(fields=['parent_label', 'level'], name='v2_product__parent__87ce16_idx'), models.Index(fields=['child_label'], name='v2_product__child_l_5cc1db_idx'), models.Index(fields=['shared_receipt'], name='v2_product__shared__829ce5_idx')],
            },
        ),
    ]
