# Generated by Django 5.1.4 on 2025-01-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infraction_details', models.TextField(help_text='위반 세부사항')),
                ('penalty_details', models.TextField(help_text='처벌 세부사항')),
                ('record_date', models.DateField(help_text='기록 날짜')),
            ],
        ),
        migrations.DeleteModel(
            name='ActionRecord',
        ),
        migrations.RemoveField(
            model_name='administrativeaction',
            name='name',
        ),
        migrations.AddField(
            model_name='administrativeaction',
            name='company_name',
            field=models.CharField(default='Unknown Company', help_text='업체명', max_length=255),
        ),
        migrations.AlterField(
            model_name='administrativeaction',
            name='action_date',
            field=models.DateField(help_text='행정처분일'),
        ),
        migrations.AlterField(
            model_name='administrativeaction',
            name='action_name',
            field=models.CharField(help_text='행정처분명', max_length=255),
        ),
        migrations.AlterField(
            model_name='administrativeaction',
            name='details',
            field=models.TextField(blank=True, help_text='기타 세부 내용'),
        ),
        migrations.AlterField(
            model_name='administrativeaction',
            name='registration_number',
            field=models.CharField(help_text='인허가번호', max_length=100),
        ),
        migrations.AddField(
            model_name='infractionrecord',
            name='administrative_action',
            field=models.ForeignKey(help_text='관련 행정처분', on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='action.administrativeaction'),
        ),
    ]
