# Generated by Django 5.1.4 on 2025-01-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_infractionrecord_delete_actionrecord_and_more'),
        ('common', '0003_administrativeaction_apiendpoint_last_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infractionrecord',
            name='administrative_action',
            field=models.ForeignKey(help_text='관련 행정처분', on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='common.administrativeaction'),
        ),
        migrations.DeleteModel(
            name='AdministrativeAction',
        ),
    ]
