# Generated by Django 5.1.4 on 2025-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_alter_infractionrecord_administrative_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='업체명', max_length=255)),
                ('action_name', models.CharField(help_text='처분명', max_length=255)),
                ('action_date', models.DateField(help_text='처분 확정일자')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_gov_name', models.CharField(help_text='지자체 이름', max_length=100, unique=True)),
                ('target_url', models.URLField(help_text='크롤링 대상 URL')),
                ('crawling_period', models.IntegerField(default=1, help_text='크롤링 주기 (일 단위)')),
                ('crawling_fields', models.CharField(help_text='크롤링 항목', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='InfractionRecord',
        ),
    ]
