# Generated by Django 5.1.4 on 2025-01-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_administrativeaction_crawlingsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeaction',
            name='details',
            field=models.TextField(blank=True, help_text='세부사항', null=True),
        ),
        migrations.AlterField(
            model_name='administrativeaction',
            name='registration_number',
            field=models.CharField(blank=True, help_text='등록번호', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crawlingsetting',
            name='crawling_fields',
            field=models.JSONField(default=dict, help_text='크롤링 항목 (JSON 필드)'),
        ),
    ]
