# Generated by Django 5.1.4 on 2025-01-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_alter_administrativeaction_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingsetting',
            name='description',
            field=models.TextField(blank=True, help_text='설명', null=True),
        ),
    ]
