

use labeldb;

CREATE TABLE country_list (
    country_code VARCHAR(3),
    country_code2 CHAR(2) PRIMARY KEY,
    numeric_code CHAR(3),
    country_name_en VARCHAR(50),
    country_name_ko VARCHAR(50)
);


INSERT INTO country_list (country_code, country_code2, numeric_code, country_name_en, country_name_ko) VALUES
('GHA', 'GH', '288', 'Ghana', '가나'),
('GAB', 'GA', '266', 'Gabon', '가봉'),
('GUY', 'GY', '328', 'Guyana', '가이아나'),
('GMB', 'GM', '270', 'Gambia', '감비아'),
('GGY', 'GG', '831', 'Bailiwick of Guernsey', '건지'),
('GLP', 'GP', '312', 'Guadeloupe', '과들루프'),
('GTM', 'GT', '320', 'Guatemala', '과테말라'),
('GUM', 'GU', '316', 'Guam', '괌'),
('VAT', 'VA', '336', 'Vatican', '교황청'),
('GRD', 'GD', '308', 'Grenada', '그레나다'),
('GRC', 'GR', '300', 'Greece', '그리스'),
('GRL', 'GL', '304', 'Greenland', '그린란드'),
('GIN', 'GN', '324', 'Guinea', '기니'),
('GNB', 'GW', '624', 'Guinea-Bissau', '기니비사우'),
('NAM', 'NA', '516', 'Namibia', '나미비아'),
('NRU', 'NR', '520', 'Nauru', '나우루'),
('NGA', 'NG', '566', 'Nigeria', '나이지리아'),
('SSD', 'SS', '728', 'South Sudan', '남수단'),
('ZAF', 'ZA', '710', 'South Africa', '남아프리카공화국'),
('NLD', 'NL', '528', 'Netherlands', '네덜란드'),
('ANT', 'AN', '530', 'Netherlands Antilles', '네덜란드령 안틸레스'),
('NPL', 'NP', '524', 'Nepal', '네팔연방'),
('NOR', 'NO', '578', 'Norway', '노르웨이'),
('NFK', 'NF', '574', 'Norfolk Island', '노퍽섬'),
('NCL', 'NC', '540', 'New Caledonia', '뉴 칼레도니아'),
('NZL', 'NZ', '554', 'New Zealand', '뉴질랜드'),
('NIU', 'NU', '570', 'Niue', '니우에'),
('NER', 'NE', '562', 'Niger', '니제르'),
('NIC', 'NI', '558', 'Nicaragua', '니카라과'),
('TWN', 'TW', '158', 'Taiwan', '대만'),
('KOR', 'KR', '410', 'Korea', '대한민국'),
('DNK', 'DK', '208', 'Denmark', '덴마크'),
('DOM', 'DO', '214', 'Dominican Republic', '도미니카공화국'),
('DMA', 'DM', '212', 'Dominica', '도미니카연방'),
('DEU', 'DE', '276', 'Germany', '독일'),
('TLS', 'TL', '626', 'Timor-Leste', '동티모르'),
('LAO', 'LA', '418', 'Laos', '라오스'),
('LBR', 'LR', '430', 'Liberia', '라이베리아'),
('LVA', 'LV', '428', 'Latvia', '라트비아'),
('RUS', 'RU', '643', 'Russia', '러시아'),
('LBN', 'LB', '422', 'Lebanon', '레바논'),
('LSO', 'LS', '426', 'Lesotho', '레소토'),
('REU', 'RE', '638', 'Reunion', '레위니옹'),
('ROU', 'RO', '642', 'Romania', '루마니아'),
('LUX', 'LU', '442', 'Luxembourg', '룩셈부르크'),
('RWA', 'RW', '646', 'Rwanda', '르완다'),
('LBY', 'LY', '434', 'Libya', '리비아'),
('LTU', 'LT', '440', 'Lithuania', '리투아니아'),
('LIE', 'LI', '438', 'Liechtenstein', '리히텐슈타인'),
('MDG', 'MG', '450', 'Madagascar', '마다가스카르'),
('MTQ', 'MQ', '474', 'Martinique', '마르티니크'),
('MHL', 'MH', '584', 'Marshall Islands', '마셜제도'),
('MYT', 'YT', '175', 'Mayotte', '마요트'),
('FSM', 'FM', '583', 'Federated States of Micronesia', '마이크로네시아연방'),
('MAC', 'MO', '446', 'Macao', '마카오'),
('MWI', 'MW', '454', 'Malawi', '말라위'),
('MYS', 'MY', '458', 'Malaysia', '말레이시아'),
('MLI', 'ML', '466', 'Mali', '말리'),
('IMN', 'IM', '833', 'Isle of Man', '맨 섬'),
('MEX', 'MX', '484', 'Mexico', '멕시코'),
('MCO', 'MC', '492', 'Monaco', '모나코'),
('MAR', 'MA', '504', 'Morocco', '모로코'),
('MUS', 'MU', '480', 'Mauritius', '모리셔스'),
('MRT', 'MR', '478', 'Mauritania', '모리타니아'),
('MOZ', 'MZ', '508', 'Mazambique', '모잠비크'),
('MNE', 'ME', '499', 'Montenegro', '몬테네그로'),
('MSR', 'MS', '500', 'Montserrat', '몬트세랫'),
('MDA', 'MD', '498', 'Moldova', '몰도바'),
('MDV', 'MV', '462', 'Maldives', '몰디브'),
('MLT', 'MT', '470', 'Malta', '몰타'),
('MNG', 'MN', '496', 'Mongolia', '몽골'),
('UMI', 'UM', '581', 'United States Minor Outlying Islands', '미국령 군소 제도'),
('VIR', 'VI', '850', 'Virgin Islands (US)', '미국령 버진아일랜드'),
('MMR', 'MM', '104', 'Myanmar', '미얀마'),
('USA', 'US', '840', 'United States of America', '미합중국'),
('VUT', 'VU', '548', 'Vanuatu', '바누아투'),
('BHR', 'BH', '48', 'Bahrain', '바레인'),
('BRB', 'BB', '52', 'Barbados', '바베이도스'),
('BHS', 'BS', '44', 'Bahamas', '바하마'),
('BGD', 'BD', '50', 'Bangladesh', '방글라데시'),
('BMU', 'BM', '60', 'Bermuda', '버뮤다'),
('BEN', 'BJ', '204', 'Benin', '베냉'),
('VEN', 'VE', '862', 'Venezuela', '베네수엘라볼리바르'),
('VNM', 'VN', '704', 'Vietnam', '베트남'),
('BEL', 'BE', '56', 'Belgium', '벨기에'),
('BLR', 'BY', '112', 'Belarus', '벨라루스'),
('BLZ', 'BZ', '84', 'Belize', '벨리즈'),
('BES', 'BQ', '535', 'Bonaire', '보네르섬'),
('BIH', 'BA', '70', 'Bosnia-Herzegovina', '보스니아헤르체고비나'),
('BWA', 'BW', '72', 'Botswana', '보츠와나'),
('BOL', 'BO', '68', 'Bolivia', '볼리비아'),
('BDI', 'BI', '108', 'Burundi', '부룬디'),
('BFA', 'BF', '854', 'Burkina Faso', '부르키나파소'),
('BTN', 'BT', '64', 'Bhutan', '부탄'),
('MNP', 'MP', '580', 'Northern Mariana Islands', '북마리아나 군도'),
('MKD', 'MK', '807', 'North Macedonia', '북마케도니아'),
('BGR', 'BG', '100', 'Bulgaria', '불가리아'),
('BRA', 'BR', '76', 'Brazil', '브라질'),
('BRN', 'BN', '96', 'Brunei', '브루나이'),
('WSM', 'WS', '882', 'Samoa', '사모아'),
('SAU', 'SA', '682', 'Saudi Arabia', '사우디아라비아'),
('CYP', 'CY', '196', 'Cyprus', '사이프러스'),
('ESH', 'EH', '732', 'Sahara Arab Democratic Republic', '사하라 아랍민주공화국(서부사하라)'),
('SMR', 'SM', '674', 'San Marino', '산마리노'),
('STP', 'ST', '678', 'Sao Tome & Principe', '상투메프린시페'),
('BLM', 'BL', '652', 'Saint Barthelemy', '생바르텔레미'),
('SPM', 'PM', '666', 'St. Pierre and Miquelon', '생피에르·미클롱'),
('SEN', 'SN', '686', 'Senegal', '세네갈'),
('SRB', 'RS', '688', 'Serbia', '세르비아'),
('SYC', 'SC', '690', 'Seychelles', '세이셸'),
('SHN', 'SH', '654', 'St Helena', '세인트 헬레나 섬'),
('LCA', 'LC', '662', 'St. Lucia', '세인트루시아'),
('', 'MF', '', 'Saint Martin', '세인트마틴 섬'),
('VCT', 'VC', '670', 'St. Vincent & the Grenadines', '세인트빈센트그레나딘'),
('KNA', 'KN', '659', 'St. Kitts-Nevis', '세인트키츠네비스'),
('SOM', 'SO', '706', 'Somalia', '소말리아'),
('SLB', 'SB', '90', 'Solomon Islands', '솔로몬제도'),
('SDN', 'SD', '736', 'Sudan', '수단'),
('SUR', 'SR', '740', 'Suriname', '수리남'),
('LKA', 'LK', '144', 'Sri Lanka', '스리랑카'),
('SWE', 'SE', '752', 'Sweden', '스웨덴'),
('CHE', 'CH', '756', 'Swiss', '스위스'),
('ESP', 'ES', '724', 'Spain', '스페인'),
('SVK', 'SK', '703', 'Slovakia', '슬로바키아'),
('SVN', 'SI', '705', 'Slovenia', '슬로베니아'),
('SYR', 'SY', '760', 'Syria', '시리아'),
('SLE', 'SL', '694', 'Sierra Leone', '시에라리온'),
('SXM', 'SX', '534', 'Sint Maarten', '신트마르턴'),
('SGP', 'SG', '702', 'Singapore', '싱가포르'),
('ARE', 'AE', '784', 'United Arab Emirates : UAE', '아랍에미리트'),
('ABW', 'AW', '533', 'Aruba', '아루바'),
('ARM', 'AM', '51', 'Armenia', '아르메니아'),
('ARG', 'AR', '32', 'Argentina', '아르헨티나'),
('ISL', 'IS', '352', 'Iceland', '아이슬란드'),
('HTI', 'HT', '332', 'Haiti', '아이티'),
('IRL', 'IE', '372', 'Ireland', '아일랜드'),
('AZE', 'AZ', '31', 'Azerbaijan', '아제르바이잔'),
('AFG', 'AF', '4', 'Afghanistan', '아프가니스탄'),
('AND', 'AD', '20', 'Andorra', '안도라'),
('ALB', 'AL', '8', 'Albania', '알바니아'),
('DZA', 'DZ', '12', 'Algeria', '알제리'),
('AGO', 'AO', '24', 'Angola', '앙골라'),
('ATG', 'AG', '28', 'Antigua and Barbuda', '앤티가바부다'),
('AIA', 'AI', '660', 'Anguilla', '앵귈라'),
('ERI', 'ER', '232', 'Eritrea', '에리트레아'),
('SWZ', 'SZ', '748', 'Eswatini', '에스와티니'),
('EST', 'EE', '233', 'Estonia', '에스토니아'),
('ECU', 'EC', '218', 'Ecuador', '에콰도르'),
('ETH', 'ET', '231', 'ETC', '에티오피아'),
('SLV', 'SV', '222', 'El Salvador', '엘살바도르'),
('GBR', 'GB', '826', 'United Kingdom', '영국'),
('ATA', 'AQ', '10', 'British Antarctic Territory', '영국령 남극지역'),
('VGB', 'VG', '92', 'British Virgin Islands', '영국령 버진 아일랜드'),
('IOT', 'IO', '86', 'British Indian Ocean Territory', '영국령 인도양 제도'),
('YEM', 'YE', '887', 'Yemen', '예멘'),
('OMN', 'OM', '512', 'Oman', '오만'),
('AUT', 'AT', '40', 'Austria', '오스트리아'),
('HND', 'HN', '340', 'Honduras', '온두라스'),
('WLF', 'WF', '876', 'Wallis and Futuna', '왈리스·퓌튀나'),
('JOR', 'JO', '400', 'Jordan', '요르단'),
('UGA', 'UG', '800', 'Uganda', '우간다'),
('URY', 'UY', '858', 'Uruguay', '우루과이'),
('UZB', 'UZ', '860', 'Uzbekistan', '우즈베키스탄'),
('UKR', 'UA', '804', 'Ukraine', '우크라이나'),
('', 'EU', '', 'European Union : EU', '유럽연합'),
('IRQ', 'IQ', '368', 'Iraq', '이라크'),
('IRN', 'IR', '364', 'Iran', '이란'),
('ISR', 'IL', '376', 'Israel', '이스라엘'),
('EGY', 'EG', '818', 'Egypt', '이집트'),
('ITA', 'IT', '380', 'Italia', '이탈리아'),
('IND', 'IN', '356', 'India', '인도'),
('IDN', 'ID', '360', 'Indonesia', '인도네시아'),
('JPN', 'JP', '392', 'Japan', '일본'),
('JAM', 'JM', '388', 'Jamaica', '자메이카'),
('ZMB', 'ZM', '894', 'Zambia', '잠비아'),
('JEY', 'JE', '832', 'Bailiwick of Jersey', '저지'),
('GNQ', 'GQ', '226', 'Equatorial Guinea', '적도기니'),
('PRK', 'KP', '408', 'North Korea', '조선민주주의인민공화국'),
('GEO', 'GE', '268', 'Georgia', '조지아'),
('CHN', 'CN', '156', 'China', '중국'),
('CAF', 'CF', '140', 'Central African Republic', '중앙아프리카'),
('DJI', 'DJ', '262', 'Djibouti', '지부티'),
('GIB', 'GI', '292', 'Gibraltar', '지브롤터'),
('ZWE', 'ZW', '716', 'Zimbabwe', '짐바브웨'),
('TCD', 'TD', '148', 'Chad', '차드'),
('CZE', 'CZ', '203', 'Czech', '체코'),
('CHL', 'CL', '152', 'Chile', '칠레'),
('CMR', 'CM', '120', 'Cameroon', '카메룬'),
('CPV', 'CV', '132', 'Cape Verde', '카보베르데'),
('KAZ', 'KZ', '398', 'Kazakhstan', '카자흐스탄'),
('QAT', 'QA', '634', 'Qatar', '카타르'),
('KHM', 'KH', '116', 'Cambodia', '캄보디아'),
('CAN', 'CA', '124', 'Canada', '캐나다'),
('KEN', 'KE', '404', 'Kenya', '케냐'),
('CYM', 'KY', '136', 'Cayman Islands', '케이맨제도'),
('COM', 'KM', '174', 'Comoros', '코모로'),
('XKX', 'XK', '383', 'Kosovo', '코소보'),
('CRI', 'CR', '188', 'Costa Rica', '코스타리카'),
('CCK', 'CC', '116', 'Cocos (Keeling) Islands', '코코스제도'),
('CIV', 'CI', '384', 'Cote D''Ivoire', '코트디부아르'),
('COL', 'CO', '170', 'Colombia', '콜롬비아'),
('COG', 'CG', '178', 'Congo', '콩고'),
('COD', 'CD', '180', 'Democratic Republic of Congo', '콩고민주공화국'),
('CUB', 'CU', '192', 'Cuba', '쿠바'),
('KWT', 'KW', '414', 'Kuwait', '쿠웨이트'),
('COK', 'CK', '184', 'Cook Islands', '쿡제도'),
('CUW', 'CW', '531', 'Curacao', '퀴라소'),
('HRV', 'HR', '191', 'Croatia', '크로아티아'),
('CXR', 'CX', '162', 'Christmas Island', '크리스마스섬'),
('KGZ', 'KG', '417', 'Kyrgyz Republic', '키르기즈공화국'),
('KIR', 'KI', '296', 'Kiribati', '키리바시'),
('TJK', 'TJ', '762', 'Tajikistan', '타지키스탄'),
('TZA', 'TZ', '834', 'Tanzania', '탄자니아'),
('THA', 'TH', '764', 'Thailand', '태국'),
('TCA', 'TC', '796', 'Turks and Caicos Islands', '터크스·케이커스 제도'),
('TGO', 'TG', '768', 'Togo', '토고'),
('TON', 'TO', '776', 'Tonga', '통가'),
('TKM', 'TM', '795', 'Turkmenistan', '투르크메니스탄'),
('TUV', 'TV', '798', 'Tuvalu', '투발루'),
('TUN', 'TN', '788', 'Tunisia', '튀니지'),
('TUR', 'TR', '792', 'Republic of Turkiye', '튀르키예공화국'),
('TTO', 'TT', '780', 'Trinidad & Tobago', '트리니다드토바고'),
('PAN', 'PA', '591', 'Panama', '파나마'),
('PRY', 'PY', '600', 'Paraguay', '파라과이'),
('PAK', 'PK', '586', 'Pakistan', '파키스탄'),
('PNG', 'PG', '598', 'Papua New Guinea : PNG', '파푸아뉴기니'),
('PLW', 'PW', '585', 'Palau', '팔라우'),
('PSE', 'PS', '275', 'Palestine', '팔레스타인'),
('FRO', 'FO', '234', 'Faroe Islands', '페로제도'),
('PER', 'PE', '604', 'Peru', '페루'),
('PRT', 'PT', '620', 'Portugal', '포르투갈'),
('FLK', 'FK', '238', 'Falkland Islands', '포클랜드 제도'),
('POL', 'PL', '616', 'Poland', '폴란드'),
('PRI', 'PR', '630', 'Puerto Rico', '푸에르토리코'),
('FRA', 'FR', '250', 'France', '프랑스'),
('GUF', 'GF', '254', 'French Guiana', '프랑스령 기아나'),
('PYF', 'PF', '258', 'French Polynesia', '프랑스령 폴리네시아'),
('FJI', 'FJ', '242', 'Fiji', '피지'),
('FIN', 'FI', '246', 'Finland', '핀란드'),
('PHL', 'PH', '608', 'Philippines', '필리핀'),
('PCN', 'PN', '612', 'Pitcairn Islands', '핏케언 섬'),
('HUN', 'HU', '348', 'Hungary', '헝가리'),
('AUS', 'AU', '36', 'Australia', '호주'),
('HKG', 'HK', '344', 'Hongkong', '홍콩');
