# Generated by Django 5.1.6 on 2026-05-02 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=10,
                        unique=True,
                        verbose_name="플랫폼",
                    ),
                ),
                (
                    "min_version",
                    models.CharField(
                        help_text="이 버전 미만이면 강제 업데이트 팝업 표시 (예: 1.2.0)",
                        max_length=20,
                        verbose_name="최소 허용 버전",
                    ),
                ),
                (
                    "latest_version",
                    models.CharField(
                        help_text="현재 스토어에 배포된 최신 버전 (예: 1.3.0)",
                        max_length=20,
                        verbose_name="최신 버전",
                    ),
                ),
                (
                    "store_url",
                    models.URLField(
                        help_text="Google Play 또는 App Store 링크",
                        verbose_name="스토어 URL",
                    ),
                ),
                (
                    "force_message",
                    models.CharField(
                        default="새로운 버전이 출시되었습니다. 업데이트 후 이용해주세요.",
                        max_length=200,
                        verbose_name="강제 업데이트 메시지",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최종 수정일시"),
                ),
            ],
            options={
                "verbose_name": "앱 버전 관리",
                "verbose_name_plural": "앱 버전 관리",
                "db_table": "mobile_app_version",
            },
        ),
        migrations.CreateModel(
            name="PushNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("keyword", "키워드 매칭"),
                            ("product", "내 제품 매칭"),
                            ("ingredient", "원료 보관함 매칭"),
                        ],
                        default="keyword",
                        max_length=20,
                        verbose_name="트리거 유형",
                    ),
                ),
                (
                    "trigger_label",
                    models.CharField(
                        blank=True,
                        help_text="매칭된 키워드 또는 제품/원료명",
                        max_length=200,
                        verbose_name="트리거 레이블",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="읽음 여부"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = 로그 생성됐지만 FCM 미발송 (배치 발송 대기 중)",
                        null=True,
                        verbose_name="FCM 발송일시",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="로그 생성일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "푸시 알림 이력",
                "verbose_name_plural": "푸시 알림 이력 목록",
                "db_table": "mobile_push_notification_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Flutter에서 생성한 UUID",
                        max_length=255,
                        unique=True,
                        verbose_name="기기 ID",
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        blank=True,
                        help_text="Firebase 푸시 알림 발송용 토큰",
                        max_length=500,
                        null=True,
                        verbose_name="FCM 토큰",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=10,
                        verbose_name="플랫폼",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, max_length=20, verbose_name="앱 버전"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="최초 등록일"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 활동일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="연결된 유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "앱 기기",
                "verbose_name_plural": "앱 기기 목록",
                "db_table": "mobile_app_device",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("click_v2_banner", "V2 배너 클릭"),
                            ("add_alert_rule", "알림 키워드 추가"),
                            ("share_news", "부적합 정보 공유"),
                            ("bookmark_news", "부적합 정보 스크랩"),
                            ("login_from_app", "앱 로그인"),
                            ("notification_open", "알림 열람"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="이벤트명",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='추가 정보 (예: {"news_id": 12, "category": "INGREDIENT"})',
                        verbose_name="파라미터",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="발생일시"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="mobile.appdevice",
                        verbose_name="기기",
                    ),
                ),
            ],
            options={
                "verbose_name": "앱 이벤트 로그",
                "verbose_name_plural": "앱 이벤트 로그 목록",
                "db_table": "mobile_analytics_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INGREDIENT", "원료/제품명"),
                            ("COMPANY", "업체명"),
                            ("ORIGIN", "원산지"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                ("keyword", models.CharField(max_length=100, verbose_name="키워드")),
                (
                    "match_type",
                    models.CharField(
                        choices=[("EXACT", "일치"), ("CONTAINS", "포함")],
                        default="CONTAINS",
                        max_length=20,
                        verbose_name="매칭 방식",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="로그인 사용자 키워드. device는 null",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유 유저",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="비회원 전용. 로그인 사용자는 user 필드 사용",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="mobile.appdevice",
                        verbose_name="기기",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 키워드",
                "verbose_name_plural": "알림 키워드 목록",
                "db_table": "mobile_alert_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="스크랩일"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="mobile.appdevice",
                        verbose_name="기기",
                    ),
                ),
            ],
            options={
                "verbose_name": "스크랩",
                "verbose_name_plural": "스크랩 목록",
                "db_table": "mobile_bookmark",
                "ordering": ["-created_at"],
            },
        ),
    ]
