# Generated by Django 5.1.6 on 2026-05-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mobile", "0001_initial"),
        ("regulatory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="regulatory.regulatorynews",
                verbose_name="부적합 정보",
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationlog",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="mobile.appdevice",
                verbose_name="기기",
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationlog",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_logs",
                to="regulatory.regulatorynews",
                verbose_name="관련 부적합 정보",
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationlog",
            name="rule_triggered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="mobile.alertrule",
                verbose_name="트리거된 키워드 규칙",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertrule",
            unique_together={
                ("device", "category", "keyword", "match_type"),
                ("user", "category", "keyword", "match_type"),
            },
        ),
    ]
