# Generated by Django 5.1.6 on 2026-02-20 18:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_document_types(apps, schema_editor):
    """기본 문서 타입 생성"""
    DocumentType = apps.get_model('products', 'DocumentType')
    default_types = [
        {'type_code': 'REPORT_MANUFACTURING', 'type_name': '품목제조보고서', 'description': '식품 품목제조보고서 또는 수입신고필증', 'detection_keywords': '품목제조보고서,제조보고,품목보고,수입신고필증', 'requires_expiry': False, 'default_validity_days': 0, 'expiry_alert_days': 30, 'is_required': True, 'display_order': 1, 'icon': 'bi-file-earmark-text', 'color': '#1a73e8', 'is_active': True},
        {'type_code': 'TEST_QUALITY', 'type_name': '자가품질검사성적서', 'description': '자가 품질 검사 성적서', 'detection_keywords': '자가품질,품질검사,성적서,검사성적서', 'requires_expiry': True, 'default_validity_days': 180, 'expiry_alert_days': 30, 'is_required': True, 'display_order': 2, 'icon': 'bi-clipboard-check', 'color': '#34a853', 'is_active': True},
        {'type_code': 'CERT_ORIGIN', 'type_name': '원산지증명서', 'description': '원료 원산지 증명서', 'detection_keywords': '원산지,원산지증명,원산지증명서', 'requires_expiry': True, 'default_validity_days': 365, 'expiry_alert_days': 30, 'is_required': True, 'display_order': 3, 'icon': 'bi-globe', 'color': '#fbbc04', 'is_active': True},
        {'type_code': 'LABEL_DESIGN', 'type_name': '한글표시사항도안', 'description': '제품 표시사항 도안 (한글)', 'detection_keywords': '표시사항,도안,한글표시,라벨', 'requires_expiry': False, 'default_validity_days': 0, 'expiry_alert_days': 30, 'is_required': True, 'display_order': 4, 'icon': 'bi-card-text', 'color': '#ea4335', 'is_active': True},
        {'type_code': 'CERT_HACCP', 'type_name': 'HACCP인증서', 'description': 'HACCP 인증서', 'detection_keywords': 'HACCP,해썹,haccp,인증서', 'requires_expiry': True, 'default_validity_days': 1095, 'expiry_alert_days': 60, 'is_required': True, 'display_order': 5, 'icon': 'bi-shield-check', 'color': '#9334e6', 'is_active': True},
        {'type_code': 'CERT_HALAL', 'type_name': '할랄인증서', 'description': '할랄 인증서', 'detection_keywords': '할랄,Halal,HALAL,halal', 'requires_expiry': True, 'default_validity_days': 730, 'expiry_alert_days': 60, 'is_required': False, 'display_order': 6, 'icon': 'bi-award', 'color': '#0d9488', 'is_active': True},
        {'type_code': 'CERT_KOSHER', 'type_name': '코셔인증서', 'description': '코셔 인증서', 'detection_keywords': '코셔,Kosher,KOSHER,kosher', 'requires_expiry': True, 'default_validity_days': 365, 'expiry_alert_days': 60, 'is_required': False, 'display_order': 7, 'icon': 'bi-award', 'color': '#0891b2', 'is_active': True},
        {'type_code': 'ANALYSIS_NUTRITION', 'type_name': '영양성분분석서', 'description': '영양성분 분석 성적서', 'detection_keywords': '영양성분,영양분석,분석서', 'requires_expiry': True, 'default_validity_days': 730, 'expiry_alert_days': 30, 'is_required': False, 'display_order': 8, 'icon': 'bi-clipboard-data', 'color': '#059669', 'is_active': True},
        {'type_code': 'SPEC_PRODUCT', 'type_name': '제품사양서', 'description': '제품 규격서 및 사양서', 'detection_keywords': '사양서,규격서,제품사양,제품규격,spec', 'requires_expiry': False, 'default_validity_days': 0, 'expiry_alert_days': 30, 'is_required': False, 'display_order': 9, 'icon': 'bi-file-earmark-ruled', 'color': '#6b7280', 'is_active': True},
        {'type_code': 'CERT_OTHER', 'type_name': '기타 인증서', 'description': '기타 인증서 및 증명서', 'detection_keywords': '인증서,인증,증명서', 'requires_expiry': True, 'default_validity_days': 365, 'expiry_alert_days': 30, 'is_required': False, 'display_order': 10, 'icon': 'bi-patch-check', 'color': '#8b5cf6', 'is_active': True},
    ]
    for type_data in default_types:
        if not DocumentType.objects.filter(type_code=type_data['type_code']).exists():
            DocumentType.objects.create(**type_data)


def remove_default_document_types(apps, schema_editor):
    """롤백: 기본 문서 타입 삭제"""
    DocumentType = apps.get_model('products', 'DocumentType')
    default_type_codes = [
        'REPORT_MANUFACTURING', 'TEST_QUALITY', 'CERT_ORIGIN', 'LABEL_DESIGN',
        'CERT_HACCP', 'CERT_HALAL', 'CERT_KOSHER', 'ANALYSIS_NUTRITION',
        'SPEC_PRODUCT', 'CERT_OTHER',
    ]
    DocumentType.objects.filter(type_code__in=default_type_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('label', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='타입 ID')),
                ('type_code', models.CharField(help_text='예: CERT_HACCP, ANALYSIS_INGREDIENT', max_length=50, unique=True, verbose_name='타입 코드')),
                ('type_name', models.CharField(help_text='예: HACCP 인증서, 성분 분석서', max_length=100, verbose_name='타입명')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='설명')),
                ('detection_keywords', models.CharField(blank=True, help_text='콤마(,)로 구분. 파일명에 이 단어가 있으면 자동 분류 (예: HACCP,해썹,haccp)', max_length=500, verbose_name='자동 분류 키워드')),
                ('requires_expiry', models.BooleanField(default=False, help_text='이 타입의 문서에 만료일이 필수인지', verbose_name='만료일 필수')),
                ('default_validity_days', models.IntegerField(blank=True, help_text='문서 업로드 시 기본 유효 기간. 0이면 무기한.', null=True, verbose_name='기본 유효 기간 (일)')),
                ('expiry_alert_days', models.IntegerField(default=30, help_text='만료 며칠 전에 알림을 보낼지', verbose_name='만료 알림 (일 전)')),
                ('is_required', models.BooleanField(default=False, help_text='이 타입의 문서가 반드시 있어야 하는지', verbose_name='필수 문서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('icon', models.CharField(default='bi-file-earmark', help_text='Bootstrap Icons 클래스명 (예: bi-file-pdf)', max_length=50, verbose_name='아이콘')),
                ('color', models.CharField(default='#6c757d', help_text='HEX 색상 코드 (예: #1a73e8)', max_length=20, verbose_name='색상')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '문서 타입',
                'verbose_name_plural': '문서 타입 목록',
                'db_table': 'v2_document_type',
                'ordering': ['display_order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='대상 필드')),
                ('content', models.TextField(max_length=2000, verbose_name='내용')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해결됨')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_comments', to='label.mylabel', verbose_name='표시사항')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.productcomment', verbose_name='상위 댓글')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL, verbose_name='해결자')),
            ],
            options={
                'verbose_name': '제품 댓글',
                'verbose_name_plural': '제품 댓글 목록',
                'db_table': 'v2_product_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('mention_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_notified', models.BooleanField(default=False, verbose_name='알림 발송됨')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='알림 발송 일시')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽음 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL, verbose_name='멘션된 사용자')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='products.productcomment', verbose_name='댓글')),
            ],
            options={
                'verbose_name': '댓글 멘션',
                'verbose_name_plural': '댓글 멘션 목록',
                'db_table': 'v2_comment_mention',
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='문서 ID')),
                ('file', models.FileField(upload_to='v2/product_documents/%Y/%m/%d/', verbose_name='파일')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기 (bytes)')),
                ('file_extension', models.CharField(blank=True, max_length=10, verbose_name='파일 확장자')),
                ('document_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='문서 제목')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='설명')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='발행일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 정보를 JSON으로 저장', verbose_name='메타데이터')),
                ('uploaded_datetime', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='products.documenttype', verbose_name='문서 타입')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_documents', to='label.mylabel', verbose_name='표시사항')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '제품 문서',
                'verbose_name_plural': '제품 문서 목록',
                'db_table': 'v2_product_document',
                'ordering': ['-uploaded_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProductFolder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False, verbose_name='폴더 ID')),
                ('name', models.CharField(max_length=100, verbose_name='폴더명')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='설명')),
                ('color', models.CharField(default='#6c757d', help_text='HEX 색상 코드 (예: #0d6efd)', max_length=7, verbose_name='폴더 색상')),
                ('icon', models.CharField(default='folder', help_text='FontAwesome 아이콘명', max_length=50, verbose_name='아이콘')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_system', models.BooleanField(default=False, help_text='삭제/이름변경 불가 (휴지통 등)', verbose_name='시스템 폴더')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_folders', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productfolder', verbose_name='상위 폴더')),
            ],
            options={
                'verbose_name': '제품 폴더',
                'verbose_name_plural': '제품 폴더 목록',
                'db_table': 'v2_product_folder',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMetadata',
            fields=[
                ('metadata_id', models.AutoField(primary_key=True, serialize=False, verbose_name='메타데이터 ID')),
                ('product_code', models.CharField(db_index=True, help_text='PRD-{user_id}-{순번}', max_length=50, unique=True, verbose_name='제품 코드')),
                ('is_starred', models.BooleanField(db_index=True, default=False, verbose_name='즐겨찾기')),
                ('starred_datetime', models.DateTimeField(blank=True, null=True, verbose_name='즐겨찾기 등록일시')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='V2에서만 사용. V1 MyLabel.delete_YN과 별도 관리', verbose_name='삭제 여부')),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_items', to='products.productfolder', verbose_name='소속 폴더')),
                ('label', models.OneToOneField(db_column='my_label_id', on_delete=django.db.models.deletion.CASCADE, related_name='v2_metadata', to='label.mylabel', verbose_name='연결된 표시사항')),
            ],
            options={
                'verbose_name': 'V2 제품 메타데이터',
                'verbose_name_plural': 'V2 제품 메타데이터 목록',
                'db_table': 'v2_product_metadata',
                'ordering': ['-updated_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProductShare',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False, verbose_name='공유 ID')),
                ('share_mode', models.CharField(choices=[('PRIVATE', '비공개 (권한 관리)'), ('PUBLIC', '공개 링크')], default='PRIVATE', max_length=20, verbose_name='공유 모드')),
                ('recipient_email', models.EmailField(blank=True, db_index=True, help_text='PRIVATE 모드에서만 사용', max_length=255, null=True, verbose_name='수신자 이메일')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='PUBLIC 모드에서 사용하는 고유 URL 토큰', unique=True, verbose_name='공개 토큰')),
                ('share_message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='공유 메시지')),
                ('share_start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='공유 시작일')),
                ('share_end_date', models.DateTimeField(blank=True, help_text='null이면 무기한', null=True, verbose_name='공유 종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_created_shares', to=settings.AUTH_USER_MODEL, verbose_name='공유자')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_shares', to='label.mylabel', verbose_name='표시사항')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='이메일이 회원인 경우 자동 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_received_shares', to=settings.AUTH_USER_MODEL, verbose_name='수신자 (회원)')),
            ],
            options={
                'verbose_name': '제품 공유',
                'verbose_name_plural': '제품 공유 목록',
                'db_table': 'v2_product_share',
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='로그 ID')),
                ('accessed_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='접근 IP')),
                ('accessed_datetime', models.DateTimeField(auto_now_add=True, verbose_name='접근일시')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('action', models.CharField(help_text='view, download, comment 등', max_length=50, verbose_name='행동')),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_share_accesses', to=settings.AUTH_USER_MODEL, verbose_name='접근자')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='products.productshare', verbose_name='공유')),
            ],
            options={
                'verbose_name': '공유 접근 로그',
                'verbose_name_plural': '공유 접근 로그 목록',
                'db_table': 'v2_share_access_log',
                'ordering': ['-accessed_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SharedProductReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False, verbose_name='수령 ID')),
                ('received_datetime', models.DateTimeField(auto_now_add=True, verbose_name='수신일시')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='수락 여부')),
                ('accepted_datetime', models.DateTimeField(blank=True, null=True, verbose_name='수락 일시')),
                ('is_used_as_ingredient', models.BooleanField(default=False, verbose_name='원료로 사용됨')),
                ('receiver_note', models.TextField(blank=True, verbose_name='수신자 메모')),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='v2_received_products', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('share', models.ForeignKey(db_column='share_id', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='products.productshare', verbose_name='공유')),
            ],
            options={
                'verbose_name': '공유 수령',
                'verbose_name_plural': '공유 수령 목록',
                'db_table': 'v2_shared_product_receipt',
                'ordering': ['-received_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SharePermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='권한 ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='보기')),
                ('can_comment', models.BooleanField(default=True, verbose_name='댓글 작성')),
                ('can_suggest', models.BooleanField(default=False, verbose_name='수정 제안')),
                ('can_use_as_ingredient', models.BooleanField(default=True, help_text='BOM에서 이 제품을 원료로 추가할 수 있는지', verbose_name='원료로 사용')),
                ('can_download_documents', models.BooleanField(default=True, verbose_name='문서 다운로드')),
                ('share', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='products.productshare', verbose_name='공유')),
            ],
            options={
                'verbose_name': '공유 권한',
                'verbose_name_plural': '공유 권한 목록',
                'db_table': 'v2_share_permission',
            },
        ),
        migrations.CreateModel(
            name='SuggestionMode',
            fields=[
                ('suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, verbose_name='대상 필드')),
                ('original_value', models.TextField(blank=True, null=True, verbose_name='원본 값')),
                ('suggested_value', models.TextField(verbose_name='제안 값')),
                ('reason', models.TextField(blank=True, max_length=1000, null=True, verbose_name='제안 사유')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '승인'), ('rejected', '거절')], default='pending', max_length=20, verbose_name='상태')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_suggestions', to='label.mylabel', verbose_name='표시사항')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='제안자')),
            ],
            options={
                'verbose_name': '필드 변경 제안',
                'verbose_name_plural': '필드 변경 제안 목록',
                'db_table': 'v2_suggestion_mode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAccessLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessed_datetime', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='label.mylabel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '제품 접근 로그',
                'db_table': 'v2_product_access_log',
                'ordering': ['-accessed_datetime'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['label', 'field_name'], name='v2_product__label_i_604c78_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['is_resolved'], name='v2_product__is_reso_d4cdc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentmention',
            unique_together={('comment', 'mentioned_user')},
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['label', 'document_type'], name='v2_product__label_i_b015fc_idx'),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['expiry_date'], name='v2_product__expiry__9edc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['is_active'], name='v2_product__is_acti_4372ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productfolder',
            unique_together={('owner', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='productmetadata',
            index=models.Index(fields=['label', 'is_deleted'], name='v2_product__my_labe_7ee7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='productmetadata',
            index=models.Index(fields=['product_code'], name='v2_product__product_1b07c5_idx'),
        ),
        migrations.AddIndex(
            model_name='productmetadata',
            index=models.Index(fields=['is_starred'], name='v2_product__is_star_0dc9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='productmetadata',
            index=models.Index(fields=['folder'], name='v2_product__folder__bcad76_idx'),
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['recipient_email'], name='v2_product__recipie_cdc293_idx'),
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['public_token'], name='v2_product__public__3b892e_idx'),
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['is_active'], name='v2_product__is_acti_59fda3_idx'),
        ),
        migrations.AddIndex(
            model_name='shareaccesslog',
            index=models.Index(fields=['share', 'accessed_datetime'], name='v2_share_ac_share_i_e4d2c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedproductreceipt',
            unique_together={('share', 'receiver')},
        ),
        migrations.AddIndex(
            model_name='suggestionmode',
            index=models.Index(fields=['label', 'field_name'], name='v2_suggesti_label_i_cf4746_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionmode',
            index=models.Index(fields=['status'], name='v2_suggesti_status_6d1ef6_idx'),
        ),
        migrations.AddField(
            model_name='sharepermission',
            name='role_code',
            field=models.CharField(choices=[('VIEWER', '단순 조회'), ('UPLOADER', '자료 제출'), ('EDITOR', '공동 편집'), ('REVIEWER', '검토자'), ('APPROVER', '승인자')], default='VIEWER', max_length=20, verbose_name='역할'),
        ),
        migrations.AddField(
            model_name='sharepermission',
            name='can_upload_documents',
            field=models.BooleanField(default=False, verbose_name='문서 업로드'),
        ),
        migrations.AddField(
            model_name='sharepermission',
            name='can_edit_label',
            field=models.BooleanField(default=False, verbose_name='정보 수정'),
        ),
        migrations.AddField(
            model_name='sharepermission',
            name='can_review',
            field=models.BooleanField(default=False, verbose_name='검토'),
        ),
        migrations.AddField(
            model_name='sharepermission',
            name='can_approve',
            field=models.BooleanField(default=False, verbose_name='승인'),
        ),
        migrations.AddField(
            model_name='productmetadata',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성 중'), ('REQUESTING', '자료 요청'), ('REVIEW', '검토 중'), ('CONFIRMED', '확정')], default='DRAFT', max_length=20, verbose_name='제품 상태'),
        ),
        migrations.AddField(
            model_name='productshare',
            name='recipient_company',
            field=models.CharField(blank=True, help_text='초대 시 입력한 회사명 (선택)', max_length=200, null=True, verbose_name='수신자 회사명'),
        ),
        migrations.AddField(
            model_name='productshare',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='초대 시 입력한 이름 (선택)', max_length=100, null=True, verbose_name='수신자 이름'),
        ),
        migrations.CreateModel(
            name='ProductActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='로그 ID')),
                ('action', models.CharField(choices=[('CREATED', '제품 생성'), ('STATUS_CHANGED', '상태 변경'), ('COMMENT_ADDED', '댓글 작성'), ('INFO_UPDATED', '정보 수정'), ('DOCUMENT_UPLOADED', '문서 업로드'), ('DOCUMENT_DELETED', '문서 삭제'), ('SHARE_CREATED', '공유 생성'), ('SHARE_UPDATED', '공유 수정'), ('SHARE_DELETED', '공유 삭제')], max_length=30, verbose_name='활동')),
                ('details', models.JSONField(blank=True, help_text='상태 변경 전/후, 댓글 내용 등', null=True, verbose_name='상세정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='label.mylabel', verbose_name='표시사항')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_activities', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '제품 활동 로그',
                'verbose_name_plural': '제품 활동 로그 목록',
                'db_table': 'v2_product_activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['label', 'created_at'], name='v2_product__label_i_756887_idx'), models.Index(fields=['user', 'created_at'], name='v2_product__user_id_853caf_idx'), models.Index(fields=['action'], name='v2_product__action_ff6d77_idx')],
            },
        ),
        migrations.AddField(
            model_name='productdocument',
            name='expiry_notification_days',
            field=models.IntegerField(default=30, verbose_name='만료 알림 기간(일)'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='expiry_notification_enabled',
            field=models.BooleanField(default=True, verbose_name='만료일 알림'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='products.productdocument', verbose_name='원본 문서'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='products.productdocument', verbose_name='대체된 문서'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='version',
            field=models.IntegerField(default=1, verbose_name='버전'),
        ),
        migrations.CreateModel(
            name='DocumentSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False, verbose_name='슬롯 ID')),
                ('status', models.CharField(choices=[('EMPTY', '미등록'), ('VALID', '정상'), ('EXPIRING', '만료임박'), ('EXPIRED', '만료됨')], default='EMPTY', max_length=20, verbose_name='상태')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('current_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_slot', to='products.productdocument', verbose_name='현재 문서')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='products.documenttype', verbose_name='문서 타입')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_slots', to='label.mylabel', verbose_name='표시사항')),
            ],
            options={
                'verbose_name': '문서 슬롯',
                'verbose_name_plural': '문서 슬롯',
                'db_table': 'v2_document_slot',
                'ordering': ['document_type__display_order', 'document_type__type_name'],
            },
        ),
        migrations.AddField(
            model_name='productdocument',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='products.documentslot', verbose_name='문서 슬롯'),
        ),
        migrations.AddIndex(
            model_name='documentslot',
            index=models.Index(fields=['label', 'status'], name='v2_document_label_i_4b7d5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentslot',
            unique_together={('label', 'document_type')},
        ),
        migrations.RunPython(
            code=create_default_document_types,
            reverse_code=remove_default_document_types,
        ),
        migrations.AddField(
            model_name='documentslot',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='이 슬롯이 숨겨졌는지 (준수율 계산에서 제외)', verbose_name='숨김'),
        ),
        migrations.AlterField(
            model_name='productmetadata',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성 중'), ('REQUESTING', '자료 요청'), ('SUBMITTED', '제출 완료'), ('REVIEW', '검토 중'), ('PENDING', '승인 대기'), ('CONFIRMED', '승인 완료')], default='DRAFT', max_length=20, verbose_name='제품 상태'),
        ),
        migrations.CreateModel(
            name='ProductNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='알림 메시지')),
                ('status_code', models.CharField(blank=True, default='', max_length=20, verbose_name='관련 상태')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='label.mylabel', verbose_name='표시사항')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '제품 알림',
                'verbose_name_plural': '제품 알림 목록',
                'db_table': 'v2_product_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='v2_product__recipie_1760a7_idx'), models.Index(fields=['label', 'created_at'], name='v2_product__label_i_c80aa1_idx')],
            },
        ),
    ]
