# Generated by Django 5.1.6 on 2026-08-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_server_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='requested_documents',
            field=models.JSONField(default=list, help_text='[{"type_id": 1, "type_name": "HACCP 인증서"}, ...]', verbose_name='요청 문서 목록'),
        ),
    ]
