# Generated by Django 5.2.17 on 2026-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ingredient_label_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productactivitylog',
            name='action',
            field=models.CharField(choices=[('CREATED', '제품 생성'), ('STATUS_CHANGED', '상태 변경'), ('COMMENT_ADDED', '댓글 작성'), ('INFO_UPDATED', '정보 수정'), ('DOCUMENT_UPLOADED', '문서 업로드'), ('DOCUMENT_DELETED', '문서 삭제'), ('SHARE_CREATED', '공유 생성'), ('SHARE_UPDATED', '공유 수정'), ('SHARE_DELETED', '공유 삭제'), ('DESIGN_COMPARED', '시안 대조')], max_length=30, verbose_name='활동'),
        ),
    ]
