# Generated by Django 5.2.17 on 2026-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sharepermission_can_view_all_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
