# Generated by Django 5.2.17 on 2026-09-12 12:18
#
# '수락' 이 두 가지를 뜻하고 있었다 — 받는 사람이 "하겠다" 고 누른 것과,
# 협력사가 파일을 낸 것이 둘 다 ACCEPTED 였다. 연락처의 '대기' 열은 PENDING
# 만 세므로, 수락만 하고 안 낸 건이 대기에서 빠져 처리된 것처럼 보였다.
#
# 이미 쌓인 ACCEPTED 중 **실제로 제출물이 있는 것만** SUBMITTED 로 옮긴다.
# 제출물이 없는 것은 하겠다고만 한 상태이므로 ACCEPTED 로 둔다 — 그래야
# 새 집계에서 다시 '대기' 로 잡힌다.

from django.db import migrations, models


def split_accepted(apps, schema_editor):
    DocumentRequest = apps.get_model('products', 'DocumentRequest')
    DocumentRequest.objects.filter(
        status='ACCEPTED', submissions__active_yn=True,
    ).distinct().update(status='SUBMITTED')


def merge_back(apps, schema_editor):
    DocumentRequest = apps.get_model('products', 'DocumentRequest')
    DocumentRequest.objects.filter(status='SUBMITTED').update(status='ACCEPTED')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_usercontact_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '요청 중'), ('ACCEPTED', '수락 (제출 전)'), ('SUBMITTED', '제출 완료'), ('REJECTED', '거절'), ('CANCELLED', '취소')], db_index=True, default='PENDING', max_length=20, verbose_name='상태'),
        ),
        migrations.RunPython(split_accepted, merge_back),
    ]
