# Generated by Django 5.2.17 on 2026-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_documentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='reminded_on',
            field=models.DateField(blank=True, null=True, verbose_name='마지막 독촉일'),
        ),
    ]
