# Generated by Django 5.2.17 on 2026-09-18 15:05

# -*- coding: utf-8 -*-
"""
구분마다 '여러 건이 쌓이는가' 를 표시하고, **원료 표시사항만** 켠다.

원료 표시사항은 장마다 다른 원료다. 그런데 업로드가 슬롯 없는 구분을 전부
'같은 구분의 옛 문서에 판으로 붙이기' 로 다뤄서, 사진을 셋 올리면 목록에는
마지막 한 줄만 남았다. 지운 적도 없는데 사라진 것으로 보인다.

**켜는 것은 하나뿐이다.** 포장지 시안은 판이 맞다 — 한 제품의 포장 디자인이
고쳐져 온 이력이고, 운영에 v7 까지 쌓여 있다. 품목제조보고서·인증서도 마찬가지다.
필요해지면 화면에서 켜면 된다.
"""
from django.db import migrations, models


def turn_on(apps, schema_editor):
    DocumentType = apps.get_model('products', 'DocumentType')
    DocumentType.objects.filter(type_code='INGREDIENT_LABEL').update(multiple_yn=True)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_expiry_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='multiple_yn',
            field=models.BooleanField(default=False, help_text='켜면 올릴 때마다 새 문서가 됩니다. 끄면 앞 문서의 새 판이 됩니다. 원료 표시사항처럼 장마다 다른 것을 담는 구분에 켭니다.', verbose_name='여러 건 허용'),
        ),
        migrations.RunPython(turn_on, migrations.RunPython.noop),
    ]
