# Generated by Django 5.1.4 on 2025-01-22 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용 (최대 1000자)', max_length=1000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_weight', models.CharField(help_text='내용량(열량)', max_length=50)),
                ('manufacturer_address', models.CharField(help_text='제조원 소재지', max_length=255)),
                ('storage_method', models.TextField(help_text='보관방법')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('api_data', models.JSONField(blank=True, help_text='API에서 가져온 데이터', null=True)),
                ('is_api_data', models.BooleanField(default=False, help_text='이 데이터가 API에서 가져온 데이터인지 여부')),
                ('manufacturer', models.CharField(db_index=True, max_length=100)),
                ('ingredients', models.TextField()),
                ('storage_conditions', models.CharField(max_length=100)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('lcns_no', models.CharField(blank=True, db_index=True, help_text='영업에 대한 허가, 등록, 신고번호 11자리', max_length=11, null=True, verbose_name='인허가번호')),
                ('bssh_nm', models.CharField(default='기본제조사명', max_length=100, verbose_name='제조사명')),
                ('prdlst_report_no', models.CharField(db_index=True, help_text='영업등록 발급연도-영업장 등록번호-영업장 제품번호', max_length=16, primary_key=True, serialize=False, verbose_name='품목제조번호')),
                ('prms_dt', models.CharField(default='yyyymmdd', help_text='yyyymmdd', max_length=8, verbose_name='허가일자')),
                ('prdlst_nm', models.CharField(db_index=True, default='기본제품명', max_length=200, verbose_name='제품명')),
                ('prdlst_dcnm', models.CharField(default='기본품목유형명', max_length=100, verbose_name='품목유형명')),
                ('production', models.CharField(blank=True, max_length=10, null=True, verbose_name='생산종료여부')),
                ('hieng_lntrt_dvs_yn', models.CharField(blank=True, max_length=10, null=True, verbose_name='고열량저영양식품여부')),
                ('child_crtfc_yn', models.CharField(blank=True, max_length=10, null=True, verbose_name='어린이기호식품품질인증여부')),
                ('pog_daycnt', models.CharField(blank=True, default='기본소비기한', max_length=200, null=True, verbose_name='소비기한')),
                ('last_updt_dtm', models.CharField(blank=True, default='yyyymmdd', max_length=8, null=True, verbose_name='최종수정일자')),
                ('induty_cd_nm', models.CharField(blank=True, default='기본업종명', max_length=80, null=True, verbose_name='업종명')),
                ('qlity_mntnc_tmlmt_daycnt', models.CharField(blank=True, max_length=100, null=True, verbose_name='품질유지기한일수')),
                ('usages', models.TextField(blank=True, max_length=4000, null=True, verbose_name='용법')),
                ('prpos', models.CharField(blank=True, max_length=200, null=True, verbose_name='용도')),
                ('dispos', models.CharField(blank=True, max_length=200, null=True, verbose_name='제품형태')),
                ('frmlc_mtrqlt', models.TextField(blank=True, max_length=300, null=True, verbose_name='포장재질')),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Food_Item',
                'indexes': [models.Index(fields=['lcns_no'], name='idx_lcns_no'), models.Index(fields=['prdlst_report_no'], name='idx_prdlst_report_no'), models.Index(fields=['prdlst_nm'], name='idx_prdlst_nm')],
            },
        ),
    ]
