# Generated by Django 5.1.4 on 2025-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='rawmtrl_nm',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='원재료명'),
        ),
    ]
