# Generated by Django 5.1.4 on 2025-02-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelingredientrelation',
            options={'ordering': ['ingredient_ratio'], 'verbose_name': '라벨-원료 관계', 'verbose_name_plural': '라벨-원료 관계들'},
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='ingredient_order',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='ingredient_purpose',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='is_main_ingredient',
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='allergen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='알레르기 물질'),
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='bssh_nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제조사명'),
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='원산지'),
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='gmo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='GMO 여부'),
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='ingredient_display_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='원료 표시명'),
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='prdlst_dcnm',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='식품유형'),
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='품목제조번호'),
        ),
    ]
