# Generated by Django 5.1.4 on 2025-02-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='label_create_YN',
            field=models.CharField(default='N', max_length=1, verbose_name='표시 사항 작성 여부'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='delete_YN',
            field=models.CharField(default='N', max_length=1, verbose_name='내 제품 삭제 여부'),
        ),
        migrations.DeleteModel(
            name='MyProduct',
        ),
    ]
