# Generated by Django 5.1.6 on 2025-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfood',
            name='korlabel',
            field=models.TextField(verbose_name='한글표시사항'),
        ),
    ]
