# Generated by Django 5.1.4 on 2025-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        # 더 이상 search_name 필드를 수정할 필요가 없으므로 빈 리스트로 만듭니다.
    ]
