# Generated by Django 5.1.4 on 2025-01-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='likers',
        # ),
        # migrations.RemoveField(
        #     model_name='fooditem',
        #     name='details',
        # ),
        # migrations.RemoveField(
        #     model_name='fooditem',
        #     name='manufacturer',
        # ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='likers',
        # ),
        migrations.AddField(
            model_name='fooditem',
            name='additional_details',
            field=models.TextField(blank=True, help_text='추가 세부사항', null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='manufacturer_name',
            field=models.CharField(default=1, help_text='제조사 이름', max_length=255),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='post',
        #     name='api_data',
        #     field=models.JSONField(blank=True, help_text='API에서 가져온 데이터', null=True),
        # ),
        # migrations.AddField(
        #     model_name='post',
        #     name='is_api_data',
        #     field=models.BooleanField(default=False, help_text='이 데이터가 API에서 가져온 데이터인지 여부'),
        # ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(help_text='카테고리', max_length=255),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='product_name',
            field=models.CharField(help_text='제품 이름', max_length=255),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='report_date',
            field=models.DateField(help_text='신고일'),
        ),
    ]
