# Generated by Django 5.1.4 on 2025-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='id',
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='relation_id',
            field=models.CharField(default='0a0', editable=False, max_length=256, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
