# Generated by Django 5.1.4 on 2025-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myingredient',
            name='search_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='검색 이름'),
        ),
    ]
