# Generated by Django 5.1.4 on 2025-02-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_mylabel_label_create_yn_alter_mylabel_delete_yn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylabel',
            name='my_label_name',
            field=models.CharField(max_length=200, verbose_name='라벨명'),
        ),
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('country_code', models.CharField(max_length=3, unique=True, verbose_name='국가코드 alpha3')),
                ('country_code2', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='국가코드 alpha2')),
                ('numeric_code', models.CharField(max_length=3, unique=True, verbose_name='국가코드 숫자')),
                ('country_name_en', models.CharField(max_length=50, unique=True, verbose_name='영문 국가명')),
                ('country_name_ko', models.CharField(max_length=50, unique=True, verbose_name='한글 국가명')),
            ],
            options={
                'db_table': 'country_list',
                'indexes': [models.Index(fields=['country_code2'], name='idx_country_code2')],
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('prdlst_dcnm', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, verbose_name='식품유형')),
            ],
            options={
                'db_table': 'FoodType',
                'indexes': [models.Index(fields=['prdlst_dcnm'], name='idx_prdlst_dcnm')],
            },
        ),
    ]
