# Generated by Django 5.1.4 on 2025-01-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_label_rawmtrl_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='rawmtrl_nm',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='원재료명'),
        ),
    ]
