# Generated by Django 5.1.4 on 2025-02-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_remove_labelingredientrelation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylabel',
            name='ingredient_ids_str',
        ),
    ]
