# Generated by Django 5.1.6 on 2025-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_importedfood_korlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfood',
            name='korlabel',
            field=models.TextField(blank=True, null=True, verbose_name='한글표시사항'),
        ),
    ]
