# Generated by Django 5.1.4 on 2025-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_labelingredientrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myingredient',
            name='ingredient_display_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='원료 표시명'),
        ),
        migrations.AddField(
            model_name='myingredient',
            name='ingredient_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='원료 비율(%)'),
        ),
    ]
