# Generated by Django 5.1.4 on 2025-01-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_fooditem_rawmtrl_nm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyUsedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='문구 카테고리')),
                ('text', models.TextField(verbose_name='문구 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdlst_report_no', models.CharField(max_length=16, unique=True, verbose_name='품목제조번호')),
                ('prdlst_nm', models.CharField(max_length=200, verbose_name='제품명')),
                ('bssh_nm', models.CharField(max_length=100, verbose_name='제조사명')),
                ('prms_dt', models.CharField(max_length=8, verbose_name='허가일자')),
                ('prdlst_dcnm', models.CharField(max_length=100, verbose_name='식품유형')),
                ('pog_daycnt', models.CharField(blank=True, max_length=200, null=True, verbose_name='소비기한')),
                ('frmlc_mtrqlt', models.TextField(blank=True, max_length=300, null=True, verbose_name='포장재질')),
                ('rawmtrl_nm', models.TextField(blank=True, max_length=1000, null=True, verbose_name='원재료명')),
                ('induty_cd_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='업종명')),
                ('hieng_lntrt_dvs_yn', models.CharField(blank=True, max_length=10, null=True, verbose_name='고열량저영양식품여부')),
            ],
        ),
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdlst_report_no', models.CharField(max_length=16, unique=True, verbose_name='품목제조번호')),
                ('prdlst_nm', models.CharField(max_length=200, verbose_name='제품명')),
                ('prdlst_dcnm', models.CharField(max_length=100, verbose_name='품목유형명')),
                ('bssh_nm', models.CharField(max_length=100, verbose_name='제조사명')),
                ('rawmtrl_nm', models.TextField(blank=True, max_length=1000, null=True, verbose_name='원재료명')),
                ('induty_cd_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='업종명')),
                ('hieng_lntrt_dvs_yn', models.CharField(blank=True, max_length=10, null=True, verbose_name='고열량저영양식품여부')),
                ('qlity_mntnc_tmlmt_daycnt', models.CharField(blank=True, max_length=100, null=True, verbose_name='품질유지기한일수')),
                ('content_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='내용량(열량)')),
                ('manufacturer_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='제조원 소재지')),
                ('storage_method', models.TextField(blank=True, null=True, verbose_name='보관방법')),
                ('distributor_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='유통전문판매원')),
                ('distributor_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='유통전문판매원 소재지')),
                ('warnings', models.TextField(blank=True, null=True, verbose_name='주의사항')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='기타 표시사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_created', models.BooleanField(default=False, verbose_name='표시사항 작성 여부')),
            ],
        ),
    ]
