# Generated by Django 5.1.4 on 2025-02-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_myingredient_ingredient_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myingredient',
            name='search_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='검색 이름'),
        ),
    ]
