# Generated by Django 5.1.4 on 2025-02-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_alter_mylabel_my_label_name_countrylist_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylist',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='국가코드 alpha3'),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='country_code2',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='국가코드 alpha2'),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='country_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='영문 국가명'),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='country_name_ko',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='한글 국가명'),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='numeric_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='국가코드 숫자'),
        ),
    ]
