# Generated by Django 5.1.4 on 2025-01-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_remove_comment_likers_remove_fooditem_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='활성 상태'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='댓글 내용 (최대 1000자)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='additional_details',
            field=models.JSONField(blank=True, help_text='추가 세부사항 (JSON 형식)', null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='manufacturer_name',
            field=models.CharField(db_index=True, help_text='제조사 이름', max_length=255),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='product_name',
            field=models.CharField(db_index=True, help_text='제품 이름', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='manufacturer',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_weight', models.CharField(help_text='내용량(열량)', max_length=50)),
                ('manufacturer_address', models.CharField(help_text='제조원 소재지', max_length=255)),
                ('storage_method', models.TextField(help_text='보관방법')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='label.fooditem')),
            ],
        ),
    ]
