# Generated by Django 5.1.6 on 2025-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_alter_importedfood_korlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfood',
            name='expirde_dtm',
            field=models.CharField(blank=True, help_text='yyyymmdd', max_length=50, null=True, verbose_name='유통기한'),
        ),
    ]
