# Generated by Django 5.1.4 on 2025-02-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_remove_mylabel_ingredient_ids_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='bssh_nm',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='ingredient_display_name',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='prdlst_dcnm',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='prdlst_nm',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='prdlst_report_no',
        ),
        migrations.RemoveField(
            model_name='myingredient',
            name='search_name',
        ),
    ]
