# Generated by Django 5.1.4 on 2025-01-28 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_frequentlyusedtext_myingredients_myproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='기타 표시사항'),
        ),
        migrations.AddField(
            model_name='label',
            name='bssh_nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제조사명'),
        ),
        migrations.AddField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='distributor_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='유통전문판매원 소재지'),
        ),
        migrations.AddField(
            model_name='label',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='유통전문판매원'),
        ),
        migrations.AddField(
            model_name='label',
            name='my_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='label.myproduct', verbose_name='연결된 내제품'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='prdlst_dcnm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='품목유형명'),
        ),
        migrations.AddField(
            model_name='label',
            name='prdlst_nm',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제품명'),
        ),
        migrations.AddField(
            model_name='label',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='품목제조번호'),
        ),
        migrations.AddField(
            model_name='label',
            name='qlity_mntnc_tmlmt_daycnt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='품질유지기한일수'),
        ),
        migrations.AddField(
            model_name='label',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='label',
            name='warnings',
            field=models.TextField(blank=True, null=True, verbose_name='주의사항'),
        ),
        migrations.AddField(
            model_name='myproduct',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 키'),
        ),
        migrations.AddField(
            model_name='myproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='content_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='내용량(열량)'),
        ),
        migrations.AlterField(
            model_name='label',
            name='manufacturer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='제조원 소재지'),
        ),
        migrations.AlterField(
            model_name='label',
            name='storage_method',
            field=models.TextField(blank=True, null=True, verbose_name='보관방법'),
        ),
        migrations.AlterField(
            model_name='myingredients',
            name='prdlst_dcnm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='식품유형'),
        ),
        migrations.AlterField(
            model_name='myingredients',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='품목제조번호'),
        ),
        migrations.AlterField(
            model_name='myingredients',
            name='prms_dt',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='허가일자'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='품목제조번호'),
        ),
    ]
