# Generated by Django 5.1.6 on 2025-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_alter_importedfood_expirde_dtm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfood',
            name='ovsmnfst_nm',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='해외제조업소'),
        ),
    ]
