# Generated by Django 5.1.4 on 2025-02-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_remove_labelingredientrelation_bssh_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelingredientrelation',
            name='relation_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
