# Generated by Django 5.1.4 on 2025-01-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_foodtype_is_active_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='manufacturer_name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='label',
            name='food_item',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='bssh_nm',
            field=models.CharField(default='기본제조사명', max_length=100, verbose_name='제조사명'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='child_crtfc_yn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='어린이기호식품품질인증여부'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='dispos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제품형태'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='frmlc_mtrqlt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='포장재질'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='hieng_lntrt_dvs_yn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='고열량저영양식품여부'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='induty_cd_nm',
            field=models.CharField(default='기본업종명', max_length=80, verbose_name='업종명'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='last_updt_dtm',
            field=models.CharField(default='yyyymmdd', max_length=8, verbose_name='최종수정일자'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='lcns_no',
            field=models.CharField(blank=True, db_index=True, help_text='영업에 대한 허가, 등록, 신고번호 11자리', max_length=11, null=True, verbose_name='인허가번호'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='pog_daycnt',
            field=models.CharField(default='기본소비기한', max_length=40, verbose_name='소비기한'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='prdlst_dcnm',
            field=models.CharField(default='기본품목유형명', max_length=100, verbose_name='품목유형명'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='prdlst_nm',
            field=models.CharField(db_index=True, default='기본제품명', max_length=200, verbose_name='제품명'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='prdlst_report_no',
            field=models.CharField(blank=True, db_index=True, help_text='영업등록 발급연도-영업장 등록번호-영업장 제품번호', max_length=16, null=True, verbose_name='품목제조번호'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='prms_dt',
            field=models.CharField(default='yyyymmdd', help_text='yyyymmdd', max_length=8, verbose_name='허가일자'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='production',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='생산종료여부'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='prpos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='용도'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='qlity_mntnc_tmlmt_daycnt',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='품질유지기한일수'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='usage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='용법'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['lcns_no'], name='idx_lcns_no'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['prdlst_report_no'], name='idx_prdlst_report_no'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['prdlst_nm'], name='idx_prdlst_nm'),
        ),
        migrations.AlterModelTable(
            name='fooditem',
            table='Food_Item',
        ),
    ]
