# Generated by Django 5.1.4 on 2025-02-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_labelingredientrelation_prdlst_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myingredient',
            name='search_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='검색 이름'),
        ),
    ]
