# Generated by Django 5.1.4 on 2025-02-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_alter_mylabel_country_of_origin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='Food_Type',
        ),
    ]
