# Generated by Django 5.1.4 on 2025-01-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_remove_fooditem_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='qlity_mntnc_tmlmt_daycnt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='품질유지기한일수'),
        ),
    ]
