# Generated by Django 5.1.4 on 2025-01-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_label_additional_info_label_bssh_nm_label_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='dispos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제품형태'),
        ),
        migrations.AddField(
            model_name='myproduct',
            name='prpos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='용도'),
        ),
    ]
