# Generated by Django 5.1.4 on 2025-02-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_myingredient_search_name'),
        ('label', '0005_alter_labelingredientrelation_relation_id'),
    ]

    operations = [
    ]
