# Generated by Django 5.1.6 on 2025-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_alter_importedfood_ovsmnfst_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfood',
            name='prduct_nm',
            field=models.TextField(blank=True, null=True, verbose_name='제품명(영문)'),
        ),
    ]
