# Generated by Django 5.1.4 on 2025-01-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_myproduct_dispos_myproduct_prpos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(default=list, verbose_name='필드 순서')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_order', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
