# Generated by Django 5.1.6 on 2025-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_alter_importedfood_prduct_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfood',
            name='prduct_korean_nm',
            field=models.CharField(max_length=300, verbose_name='제품명(한글)'),
        ),
    ]
