# Generated by Django 5.1.6 on 2025-03-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_merge_20250225_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='allergen',
        ),
        migrations.RemoveField(
            model_name='labelingredientrelation',
            name='gmo',
        ),
        migrations.AddField(
            model_name='labelingredientrelation',
            name='relation_sequence',
            field=models.IntegerField(default=1, verbose_name='원재료 순서'),
        ),
    ]
