# Generated by Django 5.1.6 on 2025-04-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0007_alter_importedfood_prduct_korean_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylabel',
            name='food_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='식품 대분류'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='food_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='식품 소분류'),
        ),
        migrations.AlterField(
            model_name='myphrase',
            name='category_name',
            field=models.CharField(choices=[('label_name', '라벨명'), ('food_type', '식품유형'), ('product_name', '제품명'), ('ingredient_info', '성분명 및 함량'), ('content_weight', '내용량'), ('weight_calorie', '내용량(열량)'), ('report_no', '품목보고번호'), ('storage', '보관방법'), ('package', '용기.포장재질'), ('manufacturer', '제조원 소재지'), ('distributor', '유통전문판매원'), ('repacker', '소분원'), ('importer', '수입원'), ('expiry', '소비기한'), ('cautions', '주의사항'), ('additional', '기타표시사항')], max_length=100, verbose_name='문구 카테고리'),
        ),
        migrations.CreateModel(
            name='AgriculturalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, verbose_name='고유번호')),
                ('category', models.CharField(max_length=50, verbose_name='구분')),
                ('item_type', models.CharField(max_length=50, verbose_name='품목 분류')),
                ('name_kr', models.CharField(max_length=100, verbose_name='명칭')),
                ('name_etc', models.CharField(blank=True, max_length=200, null=True, verbose_name='기타 명칭')),
                ('scientific_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='학명 또는 특성')),
                ('used_parts', models.CharField(blank=True, max_length=200, null=True, verbose_name='사용부위')),
                ('usage_condition', models.TextField(blank=True, null=True, verbose_name='제조 사용 조건')),
            ],
            options={
                'db_table': 'agricultural_product',
                'indexes': [models.Index(fields=['name_kr'], name='idx_agri_name_kr_index')],
            },
        ),
        migrations.CreateModel(
            name='FoodAdditive',
            fields=[
                ('category', models.CharField(max_length=100, verbose_name='식품첨가물 대분류')),
                ('name_kr', models.CharField(default='default_name_kr', max_length=200, primary_key=True, serialize=False, verbose_name='식품첨가물 명칭(한글)')),
                ('alias_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='표4 명칭+용도')),
                ('alias_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='표5 명칭 또는 간략명')),
                ('alias_6', models.CharField(blank=True, max_length=200, null=True, verbose_name='표6 명칭 또는 간략명 또는 용도')),
                ('short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='간략명')),
                ('main_purpose', models.CharField(blank=True, max_length=200, null=True, verbose_name='주용도')),
                ('color_agent', models.CharField(blank=True, max_length=10, null=True, verbose_name='착색료')),
                ('sweetener', models.CharField(blank=True, max_length=10, null=True, verbose_name='감미료')),
                ('nutrient_enhancer', models.CharField(blank=True, max_length=10, null=True, verbose_name='영양강화제')),
                ('preservative', models.CharField(blank=True, max_length=10, null=True, verbose_name='보존료')),
                ('antioxidant', models.CharField(blank=True, max_length=10, null=True, verbose_name='산화방지제')),
                ('bleaching_agent', models.CharField(blank=True, max_length=10, null=True, verbose_name='표백제')),
                ('color_fixative', models.CharField(blank=True, max_length=10, null=True, verbose_name='발색제')),
                ('stabilizer', models.CharField(blank=True, max_length=10, null=True, verbose_name='안정제')),
                ('emulsifier', models.CharField(blank=True, max_length=10, null=True, verbose_name='유화제')),
                ('thickener', models.CharField(blank=True, max_length=10, null=True, verbose_name='증점제')),
                ('coagulant', models.CharField(blank=True, max_length=10, null=True, verbose_name='응고제')),
                ('leavening_agent', models.CharField(blank=True, max_length=10, null=True, verbose_name='팽창제')),
                ('sterilizer', models.CharField(blank=True, max_length=10, null=True, verbose_name='살균제')),
                ('coating_agent', models.CharField(blank=True, max_length=10, null=True, verbose_name='피막제')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
            ],
            options={
                'db_table': 'food_additives',
                'indexes': [models.Index(fields=['name_kr'], name='idx_foodadditive_name_kr')],
            },
        ),
    ]
