# Generated by Django 5.1.6 on 2025-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0007_remove_labelingredientrelation_allergen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='recommended_label_data',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='권장 표시사항'),
        ),
    ]
