# Generated by Django 5.1.6 on 2025-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_mylabel_recommended_label_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergen',
        ),
        migrations.RemoveField(
            model_name='myingredient',
            name='ingredient_ratio',
        ),
        migrations.RemoveField(
            model_name='myingredient',
            name='my_ingredient_name',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='food_category',
            field=models.CharField(default='default_category', max_length=100, verbose_name='식품분류'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='food_group',
            field=models.CharField(default='default_group', max_length=100, verbose_name='식품군'),
        ),
        migrations.AddField(
            model_name='myingredient',
            name='allergens',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='알레르기 물질'),
        ),
        migrations.AddField(
            model_name='myingredient',
            name='gmo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='GMO'),
        ),
        migrations.AlterField(
            model_name='myingredient',
            name='ingredient_display_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='원료 표시명'),
        ),
    ]
