# Generated by Django 5.1.4 on 2025-01-30 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_allergen_remove_label_qlity_mntnc_tmlmt_daycnt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelorder',
            name='user',
        ),
        migrations.AddField(
            model_name='label',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='labels', to='label.myingredients', verbose_name='연결된 원재료'),
        ),
        migrations.AddField(
            model_name='labelorder',
            name='label',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='label.label', verbose_name='연결된 라벨'),
            preserve_default=False,
        ),
    ]
