# Generated by Django 5.1.4 on 2025-01-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_alter_fooditem_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='dispos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제품형태'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='frmlc_mtrqlt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='포장재질'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='pog_daycnt',
            field=models.CharField(default='기본소비기한', max_length=100, verbose_name='소비기한'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='prpos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='용도'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='usage',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='용법'),
        ),
    ]
