# Generated by Django 5.1.6 on 2025-04-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_alter_mylabel_food_group_alter_mylabel_food_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='chckd_additional_info',
            field=models.CharField(default='N', max_length=1, verbose_name='기타표시사항 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_bssh_nm',
            field=models.CharField(default='N', max_length=1, verbose_name='제조원 소재지 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_cautions',
            field=models.CharField(default='N', max_length=1, verbose_name='주의사항 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_content_weight',
            field=models.CharField(default='N', max_length=1, verbose_name='내용량 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_country_of_origin',
            field=models.CharField(default='N', max_length=1, verbose_name='원산지 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_distributor_address',
            field=models.CharField(default='N', max_length=1, verbose_name='유통전문판매원 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_frmlc_mtrqlt',
            field=models.CharField(default='N', max_length=1, verbose_name='용기.포장재질 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_importer_address',
            field=models.CharField(default='N', max_length=1, verbose_name='수입원 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_ingredient_info',
            field=models.CharField(default='N', max_length=1, verbose_name='성분명 및 함량 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_nutrition_text',
            field=models.CharField(default='N', max_length=1, verbose_name='영양성분 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_pog_daycnt',
            field=models.CharField(default='N', max_length=1, verbose_name='소비기한 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_prdlst_dcnm',
            field=models.CharField(default='N', max_length=1, verbose_name='식품유형 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_prdlst_nm',
            field=models.CharField(default='N', max_length=1, verbose_name='제품명 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_prdlst_report_no',
            field=models.CharField(default='N', max_length=1, verbose_name='품목보고번호 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_rawmtrl_nm_display',
            field=models.CharField(default='N', max_length=1, verbose_name='원재료명(표시) 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_repacker_address',
            field=models.CharField(default='N', max_length=1, verbose_name='소분원 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_storage_method',
            field=models.CharField(default='N', max_length=1, verbose_name='보관방법 체크'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='chckd_weight_calorie',
            field=models.CharField(default='N', max_length=1, verbose_name='내용량(열량) 체크'),
        ),
    ]
