# Generated by Django 5.1.4 on 2025-01-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0009_remove_labelorder_user_label_ingredients_and_more'),
    ]

    operations = [
    ]
