# Generated by Django 5.1.6 on 2025-03-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0009_delete_allergen_remove_myingredient_ingredient_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='mylabel',
            name='distributor_address',
        ),
        migrations.RemoveField(
            model_name='mylabel',
            name='distributor_name',
        ),
        migrations.RemoveField(
            model_name='mylabel',
            name='importer_address',
        ),
        migrations.RemoveField(
            model_name='mylabel',
            name='ingredient_create_YN',
        ),
        migrations.RemoveField(
            model_name='mylabel',
            name='recommended_label_data',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='frmlc_mtrqlt',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='포장재질'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='pog_daycnt',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='제조원 외'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='품목제조번호'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='storage_method',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='보관방법'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='type_check',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='weight_calorie',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='내용량(열량)'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='frmlc_mtrqlt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='포장재질'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='manufacturer_etc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='제조원 외'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='pog_daycnt',
            field=models.CharField(blank=True, default='기본소비기한', max_length=200, null=True, verbose_name='소비기한'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='weight_calorie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='내용량(열량)'),
        ),
        migrations.AlterField(
            model_name='myingredient',
            name='prdlst_nm',
            field=models.CharField(max_length=200, verbose_name='원료명'),
        ),
        migrations.AlterField(
            model_name='myingredient',
            name='rawmtrl_nm',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='하위 원료'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='additional_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='기타 표시사항'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='cautions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='주의사항'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='content_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='내용량'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='delete_YN',
            field=models.CharField(default='N', max_length=1, verbose_name='표시사항 삭제 여부'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='label_create_YN',
            field=models.CharField(default='N', max_length=1, verbose_name='표시사항 작성여부'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='manufacturer_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='제조원 소재지'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='storage_method',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='보관방법'),
        ),
    ]
