# Generated by Django 5.1.4 on 2025-01-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0009_alter_fooditem_dispos_alter_fooditem_frmlc_mtrqlt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='usage',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='용법'),
        ),
    ]
