# Generated by Django 5.1.4 on 2025-01-30 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0010_auto_20250130_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='unique_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='고유 키'),
        ),
    ]
