# Generated by Django 5.1.6 on 2025-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0010_remove_foodtype_food_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='calories',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='칼로리'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='carbohydrates',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='탄수화물'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='cholesterols',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='콜레스테롤'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='fats',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='지방'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='natriums',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='나트륨'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='proteins',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='단백질'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='saturated_fats',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='포화지방'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='sugars',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='당류'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='trans_fats',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='트랜스지방'),
        ),
    ]
