# Generated by Django 5.1.6 on 2025-03-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0011_mylabel_calories_mylabel_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='calories',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='칼로리'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='carbohydrates',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='탄수화물'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='cautions',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='주의사항'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='cholesterols',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='콜레스테롤'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='fats',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='지방'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='natriums',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='나트륨'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='proteins',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='단백질'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='rawmtrl_nm',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='원재료명'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='saturated_fats',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='포화지방'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='sugars',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='당류'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='trans_fats',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='트랜스지방'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='food_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='식품유형'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='rawmtrl_nm_display',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='원재료명(표시)'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='prdlst_report_no',
            field=models.CharField(db_index=True, help_text='영업등록 발급연도-영업장 등록번호-영업장 제품번호', max_length=16, primary_key=True, serialize=False, verbose_name='품목보고번호'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='pog_daycnt',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='소비기한'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='품목보고번호'),
        ),
        migrations.AlterField(
            model_name='myingredient',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='품목보고번호'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='품목보고번호'),
        ),
    ]
