# Generated by Django 5.1.4 on 2025-01-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0011_alter_fooditem_pog_daycnt_alter_fooditem_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='usage',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='usages',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='용법'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='frmlc_mtrqlt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='포장재질'),
        ),
    ]
