# Generated by Django 5.1.4 on 2025-01-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0012_remove_fooditem_usage_fooditem_usages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='frmlc_mtrqlt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='포장재질'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='usages',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='용법'),
        ),
    ]
