# Generated by Django 5.1.6 on 2025-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0012_foodtype_calories_foodtype_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylabel',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='mylabel',
            name='manufacturer_address',
        ),
        migrations.RemoveField(
            model_name='mylabel',
            name='manufacturer_etc',
        ),
        migrations.AddField(
            model_name='mylabel',
            name='distributor_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='유통전문판매원 소재지'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='importer_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='수입원 소재지'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='ingredient_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='성분명 및 함량'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='repacker_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='소분원 소재지'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='bssh_nm',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='제조원 소재지'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='prdlst_dcnm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='식품유형'),
        ),
    ]
