# Generated by Django 5.1.6 on 2025-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0014_remove_foodtype_idx_prdlst_dcnm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='food_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='식품군'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='food_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='식품유형'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='preservation_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='장기보존식품'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='processing_condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제조방법 조건'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='processing_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제조방법'),
        ),
    ]
