# Generated by Django 5.1.4 on 2025-01-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0015_alter_fooditem_usages'),
    ]

    operations = [
    ]
