# Generated by Django 5.1.6 on 2025-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0015_mylabel_food_group_mylabel_food_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='relevant_regulations',
            field=models.TextField(blank=True, null=True, verbose_name='식품유형별 관련규정'),
        ),
    ]
