# Generated by Django 5.1.4 on 2025-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0017_alter_fooditem_pog_daycnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='last_updt_dtm',
            field=models.CharField(blank=True, default='yyyymmdd', max_length=8, null=True, verbose_name='최종수정일자'),
        ),
    ]
