# Generated by Django 5.1.6 on 2025-03-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0017_remove_foodtype_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='pog_daycnt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='소비기한'),
        ),
    ]
