# Generated by Django 5.1.4 on 2025-01-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0018_alter_fooditem_last_updt_dtm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='induty_cd_nm',
            field=models.CharField(blank=True, default='기본업종명', max_length=80, null=True, verbose_name='업종명'),
        ),
    ]
