# Generated by Django 5.1.6 on 2025-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0018_alter_foodtype_pog_daycnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='calories_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='칼로리 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='carbohydrates_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='탄수화물 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='cholesterols_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='콜레스테롤 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='fats_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='지방 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='natriums_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='나트륨 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='nutrition_display_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='영양성분 표시 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='proteins_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='단백질 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='saturated_fats_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='포화지방 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='serving_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='단위 내용량'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='serving_size_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='단위 내용량 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='sugars_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='당류 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='trans_fats_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='트랜스지방 단위'),
        ),
        migrations.AddField(
            model_name='mylabel',
            name='units_per_package',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='포장 당 갯수'),
        ),
    ]
