# Generated by Django 5.1.6 on 2025-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0019_mylabel_calories_unit_mylabel_carbohydrates_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylabel',
            name='nutrition_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='영양성분 표시'),
        ),
    ]
