# Generated by Django 5.1.6 on 2025-03-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0020_mylabel_nutrition_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='prdlst_dcnm',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='식품유형명'),
        ),
    ]
