# Generated by Django 5.1.6 on 2025-03-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0022_foodtype_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='type_check',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='구분'),
        ),
    ]
