# Generated by Django 5.1.6 on 2025-04-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0024_alter_myphrase_options_remove_myphrase_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='myphrase',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_phrase', to=settings.AUTH_USER_MODEL, verbose_name='사용자 id'),
            preserve_default=False,
        ),
    ]
