# Generated by Django 5.1.6 on 2025-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0025_myphrase_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphrase',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사용조건'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='cautions',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='주의사항'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='원산지'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='food_type',
            field=models.CharField(default='default_food_type', max_length=100, primary_key=True, serialize=False, verbose_name='식품유형'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='frmlc_mtrqlt',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='포장재질'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='nutritions',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='영양성분'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='prdlst_dcnm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='식품유형명'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='prdlst_report_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='품목보고번호'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='rawmtrl_nm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='원재료명'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='storage_method',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='보관방법'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='type_check',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='weight_calorie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='내용량(열량)'),
        ),
        migrations.AlterField(
            model_name='labelingredientrelation',
            name='relation_id',
            field=models.CharField(default='default_relation', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myphrase',
            name='category_name',
            field=models.CharField(choices=[('storage', '보관방법'), ('package', '용기.포장재질'), ('manufacturer', '제조원 소재지'), ('distributor', '유통전문판매원'), ('repacker', '소분원'), ('importer', '수입원'), ('expiry', '소비기한'), ('cautions', '주의사항'), ('additional', '기타표시사항')], max_length=100, verbose_name='문구 카테고리'),
        ),
    ]
