# Generated by Django 5.1.6 on 2025-04-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0026_myphrase_note_alter_foodtype_cautions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='bssh_nm',
            field=models.CharField(default='', max_length=100, verbose_name='제조사명'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='induty_cd_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='업종명'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='last_updt_dtm',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='최종수정일자'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='pog_daycnt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='소비기한'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='prdlst_dcnm',
            field=models.CharField(default='', max_length=100, verbose_name='품목유형명'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='prdlst_nm',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='prms_dt',
            field=models.CharField(default='', help_text='yyyymmdd', max_length=8, verbose_name='허가일자'),
        ),
        migrations.AlterField(
            model_name='mylabel',
            name='pog_daycnt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='소비기한'),
        ),
    ]
